### ISSUE TITLE
Flapping of permissions by default on RHEL with source recipe

### ISSUE THREAD

**Issue by jolexa** [sous-chefs/nagios#289]
(I'm not sure if this is just poorly chosen default directories or not?)
Exhibit A: /var/log/nagios mode 755 https://github.com/tas50/nagios/blob/master/recipes/server_source.rb#L113

Exhibit B: /var/log/nagios mode 751
https://github.com/tas50/nagios/blob/master/recipes/default.rb#L208

This can be avoided in the current recipe code if the default state_dir is changed.

Same problem for conf_dir but this involves the nrpe::_source_nrpe recipe, so I'll tackle that later.

**Comment by damacus** [comment]
Fixed
