### ISSUE TITLE
apache config on Ubuntu 14.04 results in missing css style

### ISSUE THREAD

**Issue by thereforsunrise** [sous-chefs/nagios#341]
Generated apache:

<VirtualHost *:80>
  ServerAdmin     root@localhost
  ServerName      mvfdev2eae2e18.local
  DocumentRoot    /usr/share/nagios3/htdocs
  CustomLog       /var/log/apache2/nagios_access.log combined
  ErrorLog        /var/log/apache2/nagios_error.log

  Alias /stylesheets /etc/nagios3/stylesheets
  ScriptAlias /cgi-bin/nagios3 /usr/lib/cgi-bin/nagios3
  Alias /nagios3 /usr/share/nagios3/htdocs

  <Directory "/usr/lib/cgi-bin/nagios3">
     Options ExecCGI
  </Directory>

  <Location />
    AuthName "Nagios Server"
    AuthType Basic
    AuthUserFile "/etc/nagios3/htpasswd.users"
    require valid-user
  </Location>

  SetEnv TZ "UTC"

</VirtualHost>

Should be:

<VirtualHost *:80>
  ServerAdmin     root@localhost
  ServerName      mvfdev2eae2e18.local
  DocumentRoot    /usr/share/nagios3/htdocs
  CustomLog       /var/log/apache2/nagios_access.log combined
  ErrorLog        /var/log/apache2/nagios_error.log

  Alias /stylesheets /etc/nagios3/stylesheets
  Alias /nagios3/stylesheets /etc/nagios3/stylesheets
  ScriptAlias /cgi-bin/nagios3 /usr/lib/cgi-bin/nagios3
  Alias /nagios3 /usr/share/nagios3/htdocs

  <Directory "/usr/lib/cgi-bin/nagios3">
     Options ExecCGI
  </Directory>

  <Location />
    AuthName "Nagios Server"
    AuthType Basic
    AuthUserFile "/etc/nagios3/htpasswd.users"
    require valid-user
  </Location>

  SetEnv TZ "UTC"

</VirtualHost>

...or perhaps there is a better way to fix this but I don't have time to fix atm.

**Comment by caussourd** [comment]
I'm running Ubuntu 14.04 and I observed the same problem and edited the apache template this way: https://github.com/caussourd/nagios/commit/6dfd38394809fbdafd4fec7aac58baff8e1c50ec#diff-ad02592ef899b362742220bf1260cad1

As I'm not using the same Apache recipe, I didn't realize it was an Ubuntu issue... I guess it would require testing with other OS

**Comment by blueharford** [comment]
@sbotman this works, i did it locally, can it get merged into the upstream?

**Comment by sbotman** [comment]
Seems something that's only for Ubuntu. If you can make a PR for this and make sure it only targets Ubuntu, then I will be happy to merge it.

**Comment by sbotman** [comment]
@tas50 can you share your thoughts on this? (as ubuntu user)

**Comment by tas50** [comment]
I think the alias just needs to go back like @caussourd has.  For some reason Nagios really wants to not sit at the root of the site and if it does you run into issues like this.

**Comment by tas50** [comment]
Fixed in https://github.com/tas50/nagios/pull/368
