### ISSUE TITLE
Add host using custom host_template

### ISSUE THREAD

**Issue by tavorincon** [sous-chefs/nagios#345]
Hi - I am trying to use a custom host template (defined in the host_templates databag) when adding a special type of VM to Nagios following your instructions here: https://github.com/tas50/nagios/wiki/host_templates

"You then use the host template by setting the node['nagios']['host_template'] attribute for a node. You could apply this with a role as follows:

role 'windows'

default_attributes(
  nagios: {
    host_template: 'windows-host'
  }
)". 

I see that the host definition is being updated in /etc/nagios/conf.d/templates.cfg, however, when I set the node['nagios']['host_template'] attribute in my special type of VM, Nagios does not use the right host template (the one set in the node attribute), but instead it uses the default one "server".

Gustavo

**Comment by sbotman** [comment]
While looking at your issue, I thought this would be simple to fix (famous last words...)
But I was wondering of in the wrong direction before I even noticed it :)

The idea here is that you create your own template, either by using the provider or databag (like you pointed out)
On the node where you want to use this template, you specify the attribute.
If you do this via a role, make sure you converge the node first so the information is written back to the chef server.
You can check if the info is set with `knife node edit your_node_name -a`

Once this is set, the next nagios run should find the node via the search and should set this information on the host definition within the /etc/nagios/conf.d/hosts.cfg (default location)

But while I was trying to test if this really the case, my test was failing also! So I need to dive deeper into this before I can help you. We are not using different templates within production so our configuration is pretty basic. I will let you know once I found a solution for this.

**Comment by sbotman** [comment]
@tavorincon, can you please test the branch https://github.com/tas50/nagios/tree/fix_345_host_template and check if this fixes your problem? You also should use the `node['nagios']['use']` attribute on the node instead of `node['nagios']['host_template']`. I will update the documentation for this.

**Comment by tavorincon** [comment]
Hey Sander, thanks for the quick response! Let me give this branch a try
and I will get back to you soon.

Gus

**Comment by tavorincon** [comment]
Works great, thanks a lot @sbotman!

**Comment by sbotman** [comment]
Cool, will merge the branch info master and push-out a new version after I have created some tests for this. Would like to avoid this problem in the future. Please let me know if you run into any other issues because it seems that you use nagios more advanced than we do.
