### ISSUE TITLE
allow_empty_hostgroup_assignment activated on ubuntu 12.04 and package installation method

### ISSUE THREAD

**Issue by luntzel** [sous-chefs/nagios#352]
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise

This block in nagios.cfg.erb:

<% if node['nagios']['server']['install_method'] == 'source' ||
      (node['platform_family'] == 'debian' && node['platform_version'].to_i >= 7) ||
      (node['platform_family'] == 'rhel' && node['platform_version'].to_i >= 6) ||
      (node['platform_family'] == 'ubuntu' && node['platform_version'].to_f >= 14.04) -%>
allow_empty_hostgroup_assignment=1
<% end -%>

Is somehow returning true on my package installed nagios 3.2.3 and ubuntu 12.04, which barfs on the unknown variable. Please advise

**Comment by sbotman** [comment]
@petegallagher can you take a look at this?

**Comment by luntzel** [comment]
As a test, I commented out 

(node['platform_family'] == 'debian' && node['platform_version'].to_i >= 7) ||

and it worked as expected. Perhaps the debian / ubuntu versions are colliding.

**Comment by petegallagher** [comment]
Will check it out shortly and update.

**Comment by sbotman** [comment]
Tnx peter! @luntzel does this fixes your problem?

**Comment by luntzel** [comment]
That does indeed seem to fix the issue. Thank you!
