### ISSUE TITLE
/etc/nagios/conf.d/servicegroups.cfg being generated with services but no hosts

### ISSUE THREAD

**Issue by GitBytes** [sous-chefs/nagios#354]
I am running into an interesting feature.. 

Scenario:
Generating a servicegroups.cfg via (example) nagios_servicegroups/custom_servicegroup.json databag file:

```
{
  "id": "SS",
  "alias": "Some Alias",
  "notes": "SomeService Note"
}
```

and using the following (example) nagios_services/custom_service.json databag:

```
{
  "id": "SSMaster",
  "hostgroup_name": "SSMaster_list",
  "command_line": "$USER1$/check_something...",
  "servicegroups": "SS"
}
```

It would seem that when members are added to the servicegroups.cfg file, only the service description name (ex. ssmaster), is being added to the list and not ANY hosts (servicegroups.cfg):

```
line 7:      define servicegroup {
line 8:         servicegroup_name  SS
line 9:         members            ssmaster
line 10:    }
```

This breaks the nagios config check (nagios -v /etc/nagios/nagios.cfg) seemingly with output like this:

```
Nagios Core 3.5.1
Copyright (c) 2009-2011 Nagios Core Development Team and Community Contributors
...
...
Error: Could not find a service matching host name 'ssmaster' and description 'nodeX' (config file '/etc/nagios/conf.d/servicegroups.cfg', starting on line 9)
Error: Could not expand member services specified in servicegroup (config file '/etc/nagios/conf.d/servicegroups.cfg', starting on line 9)
   Error processing object config files!
```

The 'nodeX' becomes other services if they are added to the services databag with the `"servicegroups": "SS"` line.

Is my method to deploy servicegroups wrong here? Am I missing something that could allow a better or no member list to be generated? If I comment out the members line in the servicegroups.cfg file, things seem to work properly...oddly enough because of the `servicegroups       SS` line in the services.cfg file.

Any thoughts on this issue? Bottom line, members in the servicegroups.cfg file are only being populated with services and not hosts except in the case of a single service, then it grabs a seemingly random host and populates in wrong order (service,host or service,service.. instead of host,service,host,service...)

**Comment by GitBytes** [comment]
Nagios Cookbook 7.0.6

**Comment by sbotman** [comment]
Interesting issue. Will need to do some investigation on this before I can give a decent answer. Would be nice to know if you have the same problem when using version 7.0.4, because made some small changes with the last version that might break some stuff but I'm not sure... If you are able to test this quickly that would be great. Cheers Sander

**Comment by GitBytes** [comment]
Branching to do a test with previous version..however i have already tested against previous version and ran into Issue https://github.com/tas50/nagios/issues/347

I'll do it again but I suspect the create method may still be an issue there?

**Comment by sbotman** [comment]
yeah, that problem is within version 7.0.4... so no use in testing..

**Comment by sbotman** [comment]
I will try to reply your setup, that might be easier...

**Comment by GitBytes** [comment]
I apologize if my masking of exact details of databags and cfg files hinders the progress, I can report the actual bits I am using if that helps but it should be fairly accurate to help describe the use case. Just let me know if you need it, thanks!

**Comment by sbotman** [comment]
how and where do you define the servicegroup members?

**Comment by sbotman** [comment]
maybe easier if you add me on skype or something if you have time... sander.botman is my account

**Comment by GitBytes** [comment]
Will do.
Sent. Several results were there though so hopefully I got correct one?

**Comment by sbotman** [comment]
Hmm... having the exact same error here .....  So I guess your use case is sufficient to break it.. if you cannot find me on skype, try my email ping_me_now@hotmail.com

**Comment by GitBytes** [comment]
Hmm Still having issues looking you up sadly.. I sent an email to that just in case, can you confirm?

**Comment by sbotman** [comment]
Hi Ian,

Please checkout this branch and see if this will fix your problem: https://github.com/tas50/nagios/tree/fix_servicegroups

While testing I found a lot of other bugs, so was a bit more work than I expected :(

**Comment by GitBytes** [comment]
Successful test! The servicegroups.cfg members are now syncing properly!  (i.e host,service,host,service,...etc..)

Any thing else you would like from me? Otherwise I think we are ok to merge/close issue. Thanks again @sbotman and any others who may have looked over issue!

**Comment by sbotman** [comment]
Merged the code.
