### ISSUE TITLE
filter unmanaged databag items 

### ISSUE THREAD

**Issue by blueharford** [sous-chefs/nagios#356]
@sbotman 

looking for the best way to filter unmanagedhosts  in load databag. we want to only load the items that start with a attribute value

example: only load items from the data bag that start with #{node['nagios']['zone']}

unmanaged_hosts = nagios_bags.get(node['nagios']['unmanagedhosts_databag'])
unmanaged_hosts.each do |item|
  name = item['host_name'] || item['id']
  nagios_host name do
    options item
  end
end

**Comment by sbotman** [comment]
again, you will need to copy the _load_databag_config.rb into your wrapper cookbook and set the attribute to not load the default.

```
default['nagios']['server']['load_databag_config'] = false`
```

Then adjust the recipe within your wrapper and change it to something like:

```
unmanaged_hosts = nagios_bags.get(node['nagios']['unmanagedhosts_databag'])
unmanaged_hosts.each do |item|
  name = item['host_name'] || item['id']
  if name.start_with?(node['your_attribute']['here'])
    nagios_host name do
      options item
    end
  end
end
```

And then call this recipe within your wrapper cookbook.

HTH Sander

**Comment by sbotman** [comment]
Thinking about this.... this will remove one loop :)

```
unmanaged_hosts = nagios_bags.get(node['nagios']['unmanagedhosts_databag'])
unmanaged_hosts.each do |item|
  name = item['host_name'] || item['id']
  next unless name.start_with?(node['your_attribute']['here'])
  nagios_host name do
    options item
  end
end
```

**Comment by sbotman** [comment]
@blueharford Hi Joshua. Was the information here above sufficient? Please close the ticket if you have enough info. Gr Sander

**Comment by blueharford** [comment]
it looks good thanks!
