### ISSUE TITLE
check_nrpe_alive

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [sous-chefs/nagios#359]
Hi,

the cookbook defines the command "check_nrpe_alive" but sets "check-nrpe-alive" as default check-command.

best

**Comment by sbotman** [comment]
Hello @helmuthva, can you be more specific? Your right that the check-nrpe-alive is renamed to check_nrpe_alive because I wanted to have all names consistent, but I don't really understand the problem you are facing at the moment.

Tnx!
Greetings Sander

**Comment by sbotman** [comment]
@helmuthva, any update on this?

**Comment by sbotman** [comment]
This is related to ticket #397

**Comment by sbotman** [comment]
Also related to the node attributes while doing a migration. All conflicting attributes should be removed while migrating.
