### ISSUE TITLE
host_name_attribute not being honored in 7.0.8 (Chef 12)

### ISSUE THREAD

**Issue by jstange** [sous-chefs/nagios#361]
Can't seem to get this attribute to propagate down to the `@host_name_attribute` variable down in _libraries/nagios.rb_ (where it's referenced in the method `get_hostname`). Tried setting on the node with various priorities and even mangling the default in the cookbook, just to make sure I'm not being dense, and no joy. Only thing that works is modifying the default value of `@host_name_attribute` set in the `initialize` method in _libraries/nagios.rb_.

We hadn't updated the Nagios cookbook in a while, so I'm not sure when this stopped behaving. We also recently made the jump to Chef 12, so it could have something to do with that. I'm not sure what standard practice is for getting/setting attribute values within cookbook libraries, so I don't know where to start tracing. Probably a simple fix, whatever it is.

**Comment by sbotman** [comment]
This is fixed with PR #367

**Comment by sbotman** [comment]
Closing issue since it's closed with PR#367
