### ISSUE TITLE
missing nagios config line in attributes service_check_timeout_state=u

### ISSUE THREAD

**Issue by timw077** [sous-chefs/nagios#363]
Valid settings are:

c - Critical (default)
u - Unknown
w - Warning
o - OK

http://nagios.sourceforge.net/docs/3_0/configmain.html 

for example:
node['nagios']['service_check_timeout_state'] = 'u'

**Comment by GitBytes** [comment]
@sbotman Is there any chance you will be looking over this soon? Thanks in advance. If you don't have time we can do a fork thing and get by for a while until you do. Cheers!

**Comment by sbotman** [comment]
@GitBytes, do you have an suggestion? Will be happy to merge any PR. While on the subject anyway, would even be nicer if we can make a list of all the options and define some defaults. And then if the attribute exists overwrite it. This will make it very flexible.

**Comment by GitBytes** [comment]
@sbotman Cool! I will see what I can work out and get a PR out to you. Thanks.

**Comment by timw077** [comment]
Submitted pull request to fix this.  
 Thank you @GitBytes  for your help testing this.  @sbotman, Does that look good, or do you need something more?

**Comment by sbotman** [comment]
I have merged the PR, but I might change this into something more generic. Let me make a suggestion so that you can review @timw077 @GitBytes

**Comment by GitBytes** [comment]
@sbotman Thanks for taking a look. I have a plan to start working on a more fully dynamic config based on attributes chosen and be able to include the full gambit of options available but I don't have time right now, sadly.. But once I have some free time to sit down and start it I'll submit an enhancement and a pull request once complete. I'll start with the options you guys currently have so it can go in sooner, then maybe add options over time or something..

**Comment by sbotman** [comment]
@GitBytes I was thinking down the same route and was working on something today.. Will push my branch that I have currently so you can share your thoughts..

**Comment by sbotman** [comment]
See: https://github.com/tas50/nagios/compare/bugfix/363 
Idea is to iterate over all options and check if the node['nagios']['cfg']['attribute_name'] exists. Use the attribute or grab the default from the hash. And the regex is there to check the input, so we have some kind of input checking.

**Comment by GitBytes** [comment]
@sbotman, @timw077 and I were talking about this particular method and I think this is headed down a good path.

How is the versioning for this change going to be handled in your eyes? Seems like a pretty significant change to the way the main Nagios config will be handled.

Also, something I noticed while reading through.. On line 10 there seems to be "anagios" instead of just "nagios".. Not sure that was on purpose but I am betting on no, so fyi just in case.

**Comment by GitBytes** [comment]
@sbotman One suggestion we are talking about is reducing the amount of code in the list so that entries that only have a difference of the name could be in some sort of an array. Maybe that isn't necessary but thought I would throw that out there..

**Comment by sbotman** [comment]
@GitBytes, thanks for sharing your thoughts. The code I committed was really roughly and work in progress (WIP), but wanted to show the idea. 

About the version I have no thoughts yet. If the resulted config works based on the current attributes then the bumb will be minor, otherwise we need to bumb the major I guess. 

I will try to cleanup the code today so we can do some testing.

Cheers Sander

**Comment by GitBytes** [comment]
@sbotman All good, I just wanted to get what thoughts we were drumming up out there so you had the suggestion.. I will gladly do some testing for you soon/when you are ready.

**Comment by sbotman** [comment]
@GitBytes, @timw077 Finished PR https://github.com/tas50/nagios/compare/bugfix/363 This is something that can test, at least it works on my laptop :smile:. Think that the next step would be moving the attributes into default['nagios']['conf']['attribute'] where possible and needed. But for the moment it should be backwards compatible (checked all options but might have missed one)

Please let me know if this somewhat in the same line as your thoughts.
Cheers Sander

**Comment by sbotman** [comment]
@bheuvel We also discussed this issue, so maybe good if you also review and share your thoughts on this. :smile:

**Comment by GitBytes** [comment]
@sbotman I have read through the changes and it looks pretty close. I'll need to run some tests with a test branch and let you know how it plays out. Sorry I didn't get back to you sooner.. Time difference and all..

**Comment by sbotman** [comment]
@GitBytes Your review and comments are very much appreciated! If we can fine tune this, then I think we can create the same structure for the CGI settings file.

**Comment by GitBytes** [comment]
@sbotman No problem! Thanks for spending time with this. I have the changes merged, running tests now.

**Comment by sbotman** [comment]
@GitBytes Just found some attributes that I missed, so just pushed a commit with the missing attributes....

**Comment by GitBytes** [comment]
@sbotman Noted. Initial test went through and configs generated, didn't have time to compare configs yet though so I'll merge the attributes and converge and compare. So far focused on centos6.5 kitchen suite.

**Comment by GitBytes** [comment]
@sbotman I think you have a winner on this. Testing on CentOS6.5 is working, and I don't think the changes you are making will directly affect Nagios from OS to OS so unless you have another test you would like me to run it looks good! I could run the gambit of OS tests but it will take me a while to complete...

**Comment by sbotman** [comment]
@GitBytes thank for testing. Only question is if this is the right way to do it, because if we just move all settings to node['nagios']['conf']['settings'] and import all node['nagios']['conf'] settings into the config, then adding extra settings becomes much easier. We will have no input checking that way, but it might make it more flexible. So let me know your thoughts on this... Because that would mean changing the whole setup and I don't know if there are settings that I might have missed by enforcing the settings this way.

Cheers Sander

**Comment by GitBytes** [comment]
@sbotman I think the level of flexibility this method provides is a great asset, regardless of error checking, in THIS case. As long as the options provided by default are sound and also laid out plainly in the attributes file(s) then it allows end users the freedom they need to add or take away options within a wrapper environment much more easily. Really, if someone feels that with this method they want to add a non-standard line or tweak with the config or something else, they either have a good reason for it OR they need to maybe stick with the included methods via included attributes. With that said, this allows both scenarios to play out.

So one last thing we could work on is the addition of all options (commented out) to the attributes file? Maybe they would need a separate attributes file to hold them all in plain view? I see the ones to generate the default config included in the default.rb attributes file already but should we migrate those to a nagios_config.rb attributes file or something? I know of another cookbook that does this but I cannot seem to remember which one...quite frustrating as it holds a good example..

Does this help a bit? Thanks in advance.

Cheers, Ian

**Comment by bheuvel** [comment]
@sbotman Finally got round to catching up here.
Totally agree with moving the options to a settings node/attribute file for all the reasons you both ( @sbotman , @GitBytes  ) stated.

Also keeping in code the input checking or even providing defaults would be very nice, but perhaps a bit superfluous and I'm not sure if it's really worth the effort (creation/maintenance).

My vote would go for just/at least using the attributes, personally would not do input validation.

**Comment by timw077** [comment]
@sbotman, Can you bump the version, and send this to the supermarket?  
Thanks. 

TimW

**Comment by sbotman** [comment]
@timw077 I will update. Will introduce the possibility to update or add any kind of configuration item via the node['nagios']['conf'] place holder. Will move these kind of settings into a separate configuration file. Will drop the input validation so KISS and avoid future maintenance updates on this.

Cheers Sander

**Comment by timw077** [comment]
@sbotman  Perfect!  Thanks for making this happen so fast!   

Peace.

**Comment by GitBytes** [comment]
@bheuvel  Thanks for the follow-up this morning by the way.

**Comment by sbotman** [comment]
@timw077 Will continue tomorrow because it's getting late and I'm almost finished but not quite jet. Please checkout https://github.com/tas50/nagios/pull/369 that I created, which hold all the new attributes separated inside a config attribute file. I have written some tests and all should work fine. Just need to update some readme and change log and it's ready to merge. @bheuvel, @timw077 and @GitBytes comments are appreciated :) 

Cheers Sander

**Comment by GitBytes** [comment]
@sbotman as always, thanks for your time sir!

**Comment by bheuvel** [comment]
Put my comment in the pull request #369

**Comment by sbotman** [comment]
@timw077 With PR https://github.com/tas50/nagios/pull/369 your request is moved under `default['nagios']['conf']['service_check_timeout_state']` 
Hope that you don't mind the change, but with this update you are able to set/change/remove/create any config option you want :smile: 
With this I'm closing this issue, with special thanks to @timw077 @GitBytes @bheuvel for your support!

**Comment by GitBytes** [comment]
@sbotman @bheuvel A huge thanks to you both, you guys did a lot of work with this and I greatly appreciate all of your time and effort to enable this new feature!!  I think users will like the ability to better customize things as they see fit. I was happy to give input where I could. Until next time.. Cheers!
