### ISSUE TITLE
Add v7.1.1 tag

### ISSUE THREAD

**Issue by leoditommaso** [sous-chefs/nagios#377]
Please, release a new version including fixes in PR #368, #374 and #375.

Thanks!

**Comment by tas50** [comment]
7.1.2 is out

**Comment by sbotman** [comment]
Awesome Tim! Was about to do this after diner, but you beat me to it :) Tnx dude!

Sent from my iPhone

On 01 May 2015, at 19:50, Tim Smith <notifications@github.com<mailto:notifications@github.com>> wrote:

7.1.2 is out
