### ISSUE TITLE
Not adding pagerduty contact to every group

### ISSUE THREAD

**Issue by jhammerman79** [sous-chefs/nagios#385]
Hi Nagios cookbook maintainers,

Thank you for the cookbook! I'm trying to use the wrapper development method to alter some of the logic in the cookbook. Specifically, I would like to control the members in contactgroups, and be able to exclude the pagerduty user  (not every alert is a paging alert in my setup).

I put together something like this:

http://pastebin.com/awwGZtk2

At this point I could open up the compiled contactgroups.cfg and rerender it (can't just call nagios_conf on it due to the duping behavior). I can't follow the logic of where nagios_contactgroup LWRP stores the MASH it creates though. Accordingly, I do not know what to pass into the services.cfg.erb.

Any assistance is greatly appreciated!
Joe Hammerman

**Comment by jhammerman79** [comment]
I wanted to mark this as a question, but I don't see a facility for that - perhaps it is an administrative function?

**Comment by sbotman** [comment]
Will be happy to help, only today and tomorrow free.. Let's contact next week... Cheers Sander

**Comment by sbotman** [comment]
Your code on pastebin looks good! 

The contact group information is stored on Nagios.instance.contactgroups hash, so when you debug this, you should be able to query this.

Maybe the wiki can answer your question about the services. 
https://github.com/tas50/nagios/wiki/services.cfg

Or reach out and contact us on https://gitter.im/tas50/nagios.

**Comment by sbotman** [comment]
Should be fixed within version 7.1.4. Closing this for the moment but feel free to reopen if you still run into errors.
