### ISSUE TITLE
support read only users

### ISSUE THREAD

**Issue by blueharford** [sous-chefs/nagios#390]
@sbotman To provide rouser with rights to see stuff, simply edit your nagios cgi file normally found in /usr/local/nagios/etc/cgi.cfg. Look for the directives

authorized_for_all_services=nagiosadmin
authorized_for_all_hosts=nagiosadmin

And add next to it with a comma, the rouser which you just created like below:

authorized_for_all_services=nagiosadmin,rouser
authorized_for_all_hosts=nagiosadmin,rouser

have a attribute be the group for readonly users vs the admin group.

i'd like to give more people access to nagios without allowing them the ability to mute or disable anything

**Comment by sbotman** [comment]
So you are asking me to fix this? Or are you going to create a PR for me to review :)?

**Comment by sbotman** [comment]
Quickly looking at this, these options are set with attirbutes:

```
authorized_for_all_services=<%= node['nagios']['cgi']['authorized_for_all_services'] %>
authorized_for_all_hosts=<%= node['nagios']['cgi']['authorized_for_all_hosts'] %>
```

So you could set this attribute to "nagiosadmin,rouser" to achieve the desired result.
Or am I missing something?

**Comment by blueharford** [comment]
more looking for your opinion in how 
to add in the read only user permission

**Comment by blueharford** [comment]
http://highsecurity.blogspot.com/2009/07/nagios-read-only-user.html

**Comment by sbotman** [comment]
Join me on [![Join the chat at https://gitter.im/schubergphilis/nagios](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/schubergphilis/nagios?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and lets discuss..

**Comment by sbotman** [comment]
We just moved the repo into the area of Schuberg Philis, but I think that we are missing some messages on gitter, please repeat your question about the hosts....

**Comment by sbotman** [comment]
Hi @blueharford, think that we never had a chat about this or I don't remember. Is this issue still open or did you find a solution for your problem? Please share :)

**Comment by blueharford** [comment]
@sbotman i havent found a solution, just changed our nagios from htaccess to ldap. so its sometihng i am going to be investigating asap.

**Comment by sbotman** [comment]
Great, let me know if I can help you with something...

**Comment by wilb** [comment]
According to the docs at https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/configcgi.html this should be do-able by simply adding an "authorized_for_read_only=" line to the cgi.cfg and passing in the users that are allow read only access?
