### ISSUE TITLE
nagios_host defined hosts removed from search results

### ISSUE THREAD

**Issue by jhammerman79** [sous-chefs/nagios#395]
Hello Nagios cookbook development team,

Following this:

To create hosts, you can use the nagios_host provider within your recipes.

From here:

https://github.com/tas50/nagios/wiki/hosts.cfg

I thought that I could define hosts and hostgroups with relying on the search function (useful for me since I am in the process of a rollout, and I don't know that my Chef groups will match up exactly with my Nagios hostgroups. I also didn't want to roll Chef out everywhere and introduce a bunch of empty cookbooks simply to get the results returned to the Nagios server. However, nagios_host defined hosts didn't show up in the hosts.cfg (I have load default config turned off, so it is not a resource cloning issue).

Since this functionality was broken, I installed teh dummy roles, and performed chef-client runs on all the machines so that they would turn up in search. I added a puts here:

nodes.each { |n| puts "#{n}"; Nagios.instance.push(n) }

So I know for a fact that all of the nodes that end up missing from the hosts.cfg are being returned in the Chef node search.

The thing that all of the nodes that end up missing have in common is that they are all defined in a recipe I made (the behavior of nodes going missing is the same whether the recipe is included before or after the search).

Here is a sample nagios_host definition:

nagios_host 'inf1' do
  options 'name'        => 'inf1.stg.prv',
          'address'     => '172.16.1.11',
          'hostgroups'  => 'non-physical'
end

Am I doing something wrong? Am I misinterpreting something? If nagios_host doesn't create nodes and that is by design, then the wiki is confusingly worded.

Please let me know if this is indeed a bug. I am going to post my recipes and sample outputs to a Pastebin.   

Please let me know if there is more information that I can supply in order to assist in determining the error condition.

Thanks,
Joseph Hammerman

**Comment by jhammerman79** [comment]
Pastebin with my configs is here:

http://pastebin.com/KtMsUsLY

**Comment by jhammerman79** [comment]
Update: these hosts are all getting written into the termplates.cfg - is that intentional?

**Comment by jhammerman79** [comment]
More color: even when defined thusly:

nagios_host 'inf1' do
  options 'name'        => 'inf1.stg.prv',
          'use'         => 'server',
          'address'     => '172.16.1.11',
          'hostgroups'  => 'non-physical',
          'register'    => 1
end

The host is rendered in templates.cfg as:

define host {
  name        inf1.stg.prv
  use         server
  host_name   inf1
  hostgroups  inf,linux,non-physical,staging
  address     172.16.1.11
  register    0
}

How does one regist a host defined using the nagios_host LWRP?

**Comment by TheCase** [comment]
re: "these hosts are all getting written into the termplates.cfg - is that intentional?"

if you include a host/service option of 'name', it will add it as a template.  You might want to change 'name' to 'alias' in this case if you want to get it into hosts.cfg

**Comment by jhammerman79** [comment]
Thanks, that solved the problem!

Shall I close this ticket and open a new one against the documentation? Feels like it should be mentioned that this will occur.

Thanks,
Joseph Hammerman

**Comment by sbotman** [comment]
Hi Joseph,

Will close the ticket because I have updated the wiki to be more clear about this.
Feel free to reopen the ticket if you have more remarks about this.

Cheers Sander
