### ISSUE TITLE
Nginx config broken for Ubuntu 12.04

### ISSUE THREAD

**Issue by jhammerman79** [sous-chefs/nagios#396]
Hi Nagios Cookbook devs,

In Ubuntu, after the nagios3.conf is dropped off, using the php dispatcher, I encountered the following issues:

This directive:

fastcgi_pass  unix:/var/run/nginx/phpwrap-dispatch.sock;

Should read:

fastcgi_pass  unix:/var/run/nginx/phpwrap-dispatch_sock;

And there's no cgi block, so Nginx looks in /usr/share/nagios3/htdocs for a cgi-bin directory.

I added this:

location ~ .cgi$ {
                root /usr/lib/cgi-bin/nagios3;

```
            rewrite ^/cgi-bin/nagios3/(.*)$ /$1;

            include /etc/nginx/fastcgi_params;

            fastcgi_param AUTH_USER $remote_user;
            fastcgi_param REMOTE_USER $remote_user;
            fastcgi_param SCRIPT_FILENAME /usr/lib/cgi-bin/nagios3$fastcgi_script_name;

            fastcgi_pass 127.0.0.1:8999;
    }
```

And a fcgi listener on port 8999, and everything is copacetic.

Have I missed something here, or are these valid issues?

Thanks,
Joseph Hammerman

**Comment by sbotman** [comment]
Hi Joseph,

Which installation of nagios are you using, the package or the source installation?
Would be nice to have some tests that check this, but I'm not a Ubuntu engineer.
Can you provide a PR with the needed changes?

Cheers Sander

**Comment by jhammerman79** [comment]
Hi sbotman,

The installation method is default, which I believe is package.

I'd be happy to help, but I have to admit I have trouble reading the code for this cookbook.

Where are you calling the template to be rendered? And where do you set the string value to be rendered for the PHP socket?

I had to put in an fcgi server & dispatch as well. It's possible that I'm missing something, since as I understand it the cookbook lets you use php or cgi or both. However the paths to the images were broken. Again, I can submit code that installs an fcgi wrapper, but I'm not sure if that's what you want.

One final note, I had to overwrite url_html_path in nagios.conf. I believe that that value shoudl be decoupled from the vname of the host, as they are not conceptually intertwined.
Joe

**Comment by sbotman** [comment]
Hi @jhammerman79 
A while ago we have changed the nagios config creation so that it will grab all the settings you set under default['nagios']['conf']['your_settings']
So you should be able to change the fastcgi_pass just by adding the attribute on the nagios server.
Is this solving the problem above or is this issue something different?

**Comment by sbotman** [comment]
@jhammerman79 I close this ticket because I think it's solved with my comment here above. Please feel free to reopen the ticket if you still have problems with this. KR, Sander
