### ISSUE TITLE
Setting custom macros

### ISSUE THREAD

**Issue by jhammerman79** [sous-chefs/nagios#399]
Hi Nagios cookbook development team,

Nagios has a provision for custom macros:

http://nagios.sourceforge.net/docs/3_0/customobjectvars.html

I need to set this for my redis checks to function:

http://support.nagios.com/forum/viewtopic.php?f=7&t=26608

I tried this:

nagios_host 'rds1' do
  options 'alias'        => 'rds1.stg.prv',
          'address'     => '172.16.2.40',
          'hostgroups'  => 'rd_secondaries,redis',
          '_SYSTEM_MEMORY'  => '3G'
end

But the rendered file tosses the value out.

Would this work if I created a template and inherited from that? Or is there some other facility for effecting this?

I could open open up the hosts.cfg and rerender it with custom values, but Sander and I tried to do that with contacts.cfg in bug #395, and we had no joy.

Thanks in advance for any assistance you can provide,
Joseph Hammerman

**Comment by sbotman** [comment]
Hi @jhammerman79, did you find any solution/work around for this or is this issue still open?

**Comment by sbotman** [comment]
@jhammerman79 I have fixed this issue on branch: https://github.com/schubergphilis/nagios/tree/enable_custom_options
Only want to add some tests before creating a pull request for this one.
But this should solve your problem.

Gr Sander

**Comment by sbotman** [comment]
branch is merged so will close this ticket. Please feel free to reopen the ticket if you still experience issues.
