### ISSUE TITLE
using public IP for nodes outside VPC but still in the same cloud

### ISSUE THREAD

**Issue by veilig2000** [sous-chefs/nagios#400]
If my nagios is inside a VPC in the cloud (EC2), and I have nodes in the same cloud (EC2) but not in the VPC, is there a way to tell nagios to define the host of the nodes **NOT** in the VPC to use their public IP instead of their private? 

It appeared to me the only way would be to change the provider attribute to something different.

https://github.com/schubergphilis/nagios/blob/ac84639957aec7039c12bc6875c510b32975ccb5/libraries/default.rb#L43

I realize I could change my `cloud['provider']` attribute of those nodes, but I'm not sure what sort of ramifications that would have?

**Comment by sbotman** [comment]
You should be able to override the default['nagios']['address'] field per node for the IP address that you want to use to connect to from your nagios server. Please let me know if this solves your problem.

**Comment by isavoy** [comment]
Is this not how the host's address attribute is being set?

https://github.com/schubergphilis/nagios/blob/ac84639957aec7039c12bc6875c510b32975ccb5/libraries/nagios.rb#L288

Could the logic from the ip_to_monitor function be integrated into the push_node function? If that happened, we could define a separate cloud provider in ohai hints for vpc, and add logic to ip_to_monitor to differentiate between ec2-classic and vpc. With so many people on ec2 experimenting with and migrating to vpc, this would be a small change that would make patching this easier for those of us with specific needs.

**Comment by sbotman** [comment]
Yes, but the line below your pointer will overrule the address if the node['nagios']['address'] field is populated. So setting this field with your desired IP address should fix the IP problem.
We can also use the ip_to_monitor function as you suggest, will create a PR for that.

Gr Sander

**Comment by sbotman** [comment]
Have closed my pull request because I don't like the solution. Really want to review this solution and think about a proper implementation. If somebody could help me with this, I would really appreciate this!
