### ISSUE TITLE
Missing symlinks

### ISSUE THREAD

**Issue by shurab** [sous-chefs/nagios#401]
I have a following issue with nagios master branch when running 'kitchen converge' command. For simplicity sake I left in '.kitchen.yml' file platform section for centos-6.6 and use either server-server or server_source suite. In result I have this error: 

> > > > > ------Exception-------
> > > > >                         Class: Kitchen::ActionFailed
> > > > >                         Message: Failed to complete #converge action: [No such file or directory @ rb_file_s_stat - /var/folders/nt/xx63rhw136qg7ft3qybr_j4c0000gp/T/server-package-centos-66-sandbox-20150602-75321-1lbz0pl/cookbooks/nagios/test/integration/server_package/bats]
> > > > >                         Please see .kitchen/logs/kitchen.log for more details
> > > > >                         Also try running kitchen diagnose --all for configuration

The only option to fix it to replace symlink /test/integration/server_package/bats by real files.
Can someone make a comment about it? Does it a bug?
I run everything on Mac OS X with latest chefdk 0.6.0.

**Comment by shurab** [comment]
I followed @sbotman advice and run these commands:

```
bundle install --path vendor
bundle exec kitchen converge server-package-centos-66
```

Unfortunately, the same error. It appear that kitchen does not follow symliks in test/integration/ tree.

**Comment by bheuvel** [comment]
Apparently Test-Kitchen and symlinks don't always work as expected: test-kitchen/test-kitchen#503

A PR was made to provide cross-test code: test-kitchen/test-kitchen#134 but that doesn't actually execute the "crossed" tests ( see last comment of bbergstrom in test-kitchen/busser-serverspec#26 )

**Comment by sbotman** [comment]
I will close this issue because it's more related to kitchen as I understand the above correctly. But please feel free to reopen this if I interpreted this incorrectly.
