### ISSUE TITLE
exclude_tag_host not being honored

### ISSUE THREAD

**Issue by bphinney** [sous-chefs/nagios#402]
Docs suggest that setting a node['nagios']['exclude_tag_host'] attribute to a specific tag will cause all hosts that have that tag to be excluded from monitoring.  However, apparently, that specific attribute is not being referenced in any of the providers nor is it honoring that setting and excluding hosts that are tagged as such.

**Comment by snkutlu** [comment]
@bphinney I will have a look on this.

**Comment by darrencassar** [comment]
@snkutlu any news on this bug?

**Comment by sbotman** [comment]
@snkutlu please check https://github.com/schubergphilis/nagios/tree/exclude_tag_host 
Still need to write some tests for this....

**Comment by sbotman** [comment]
@darrencassar can you please look at pull request: https://github.com/schubergphilis/nagios/pull/412 
Think this will solve your problem, please let me know.

**Comment by darrencassar** [comment]
Works like a charm - thank you :+1:

**Comment by sbotman** [comment]
Cool, only need the review from @snkutlu and hopefully he will merge it for me...

**Comment by sbotman** [comment]
Code is merged within master with PR #412 and even bug fixed with PR #414. Closing issue.
