### ISSUE TITLE
services: `activate_check_in_environment` broken

### ISSUE THREAD

**Issue by m-tse** [sous-chefs/nagios#404]
In the services data bag [section](https://github.com/schubergphilis/nagios/wiki/services) there is a field called `activate_check_in_environment` which lets you specify that a check only applies to a certain chef environment.  It seems this functionality was removed in some recent commit, and the README has not been updated.

In my fork, I implemented a quick [fix](https://github.com/firebase/nagios/commit/ebfe6101ca02c09b0a40db6fc53dc7e34d18b840#diff-888ebea5be81efe270460f5bd06c5ce6R43) putting this functionality back in.

**Comment by sbotman** [comment]
This fix was merged into master, closing this issue.
