### ISSUE TITLE
nagios node hostname -> node.name?

### ISSUE THREAD

**Issue by zetan503** [sous-chefs/nagios#407]
I love the chef -> nagios auto config. However the windows nodes are reporting their NetBIOS hostname and I'd rather have them report their chef node.name. I can't figure out where to make that change. Can you advise?

Thanks
-Zetan

**Comment by sbotman** [comment]
Hi Zetan,

The chef nodes are loaded within the default config recipe, here:
https://github.com/schubergphilis/nagios/blob/master/recipes/_load_default_config.rb#L43

So while importing the node objects via push the push_node is done, here:
https://github.com/schubergphilis/nagios/blob/master/libraries/nagios.rb#L178

And for the hostname the get_hostname is called here:
https://github.com/schubergphilis/nagios/blob/master/libraries/nagios.rb#L284

So you have some options within the get_hostname function here:
https://github.com/schubergphilis/nagios/blob/master/libraries/nagios.rb#L273

You can either set the name you want on the chef-node object under and this will overrule all others:
node: node['nagios']['host_name'] = "your name"

You can set the host_name attribute, which by default is "hostname" on your Nagios Server, by setting:
nagios_server: node['nagios']['host_name_attribute']  = "your attribute" 
Setting this to 'name' will use the chef-node name as the names for your nagios configuration.

Hope that this answers your question.
GR Sander

**Comment by sbotman** [comment]
Closing this issue, but please feel free to reopen if you have more questions about this.

**Comment by zetan503** [comment]
Hi sorry for the long delay,

In my nagios wrapper cookbook, I have this set in attributes/default.rb
default['nagios']['host_name_attribute'] = 'name'

However the names are still coming out with hostname.

knife search node 'name:ord12-p-cxpr-dir-01' -Fj |grep hostname
    "hostname": "ORD12PCXPRDIR01",

knife search node 'name:ord12-p-cxpr-dir-01'
Node Name:   ord12-p-cxpr-dir-01

define host {
  use         server
  host_name   ORD12PBDCSDIR01
... etc

Am I setting the variable incorrectly?

**Comment by sbotman** [comment]
which version of the cookbook are you using?

**Comment by zetan503** [comment]
Was 7.1.2 then pulled down 7.2.0 yesterday

**Comment by sbotman** [comment]
interesting... please join me on gitter and lets chat... https://gitter.im/schubergphilis/nagios
