### ISSUE TITLE
unmanagedhosts environment key does nothing

### ISSUE THREAD

**Issue by sethrutnertrr** [sous-chefs/nagios#408]
I am monitoring a device through a data-bag in unmanaged hosts and I wish to only monitor this device in the _default environment.  JSON is as so:

{
  "address": "10.1.99.1",
  "hostgroups": ["switches"],
  "id": "SF-SRX240",
  "environment":  "_default",
  "notifications": 1,
  "host_template": "generic-switch"
}

However, I have a monitoring server in environment 'New_Jersey' and this device and other continue to show up in config files.  This problem also goes the other way, if the environment is set to 'New_Jersey' it will appear in the config files for the '_default' environment.

Is this functionality broken?

**Comment by sethrutnertrr** [comment]
OK I was able to create a fix by changing the following in _load_databag_config.rb


 @@ -138,8 +138,10 @@
 
 unmanaged_hosts = nagios_bags.get(node['nagios']['unmanagedhosts_databag'])
 unmanaged_hosts.each do |item|
-  name = item['host_name'] || item['id']
-  nagios_host name do
-    options item
+	if item['environment'].nil? || item['environment'] == node.chef_environment
+	  name = item['host_name'] || item['id']
+	  nagios_host name do
+    	  options item
+    end
   end
 end

**Comment by sethrutnertrr** [comment]
I was able to create a fix for this here https://github.com/sprutner/nagios/commit/78f97c284f7fb363bb482fb32a3de744ab2613df

**Comment by sbotman** [comment]
I have merged your fix within master. Had to fix the checkstyle, but if all tests are green I will push out a new version with our fix.

**Comment by sethrutnertrr** [comment]
Sweet, my first merge/fix.

On Wed, Aug 12, 2015 at 5:23 AM, Sander Botman notifications@github.com
wrote:

> I have merged your fix within master. Had to fix the checkstyle, but if
> all tests are green I will push out a new version with our fix.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/schubergphilis/nagios/issues/408#issuecomment-130281429
> .

## 

---

Seth Rutner
Systems Engineer
The RealReal | therealreal.com

**Comment by sbotman** [comment]
And thank you for pointing this out, your help is greatly appreciated!
