### ISSUE TITLE
using commas in nagios_service "check_command" option breaks stuff unexpectedly

### ISSUE THREAD

**Issue by TheCase** [sous-chefs/nagios#411]
example (_checks-test.rb):

```
nagios_command 'system-load' do
  options 'command_line'    => '$USER1$/check_load -w $ARG1$ -c $ARG2$'
end

nagios_service 'system-load' do
  options 'check_command'       => 'system-load!15,10,5!30,25,20',
          'use'                 => 'default-service',
          'hostgroup_name'      => 'linux'
end
```

results in this in _services.cfg_: 

```
define service {
  use                  default-service
  service_description  system-load
  hostgroup_name       linux
  check_command        20
}
```

Also, something else funky is happening, as I see this show up in the _commands.cfg_ file:

```
# Skipping 10 because command_line is missing.

# Skipping 20 because command_line is missing.

# Skipping 25 because command_line is missing.

# Skipping 5!30 because command_line is missing.

# Skipping system-load!15 because command_line is missing.
```

If I drop the commas from the check_command option, everything works as expected: with the exception that I still see a comment in the commands.cfg file:
`# Skipping system-load!15!30 because command_line is missing.`

I'm not sure if other characters or symbols might break as well.  I'm still researching, but wanted to report the issue.

**Comment by sbotman** [comment]
Thats indeed strange behaviour.. Will need to investigate why this happens... 
Please let me know if you find some pointers

**Comment by TheCase** [comment]
In regards to the odd output in commands.cfg, it looks like the **check_command** option is mistaken for a **nagios_command** stanza during the **_find_object**_ phase in **libraries/nagios.rb**

using _-l debug_ switch during kitchen converge:

```
   [2015-08-17T21:29:22+00:00] DEBUG: Loading Recipe tec-nagios::_checks-test via include_recipe
   [2015-08-17T21:29:22+00:00] DEBUG: Found recipe _checks-test in cookbook tec-nagios
   [2015-08-17T21:29:22+00:00] DEBUG: Nagios debug: Creating entry for Nagios::Command with name: system-load
   [2015-08-17T21:29:22+00:00] DEBUG: Nagios debug: Creating entry for Nagios::Service with name: system-load
   [2015-08-17T21:29:22+00:00] DEBUG: Nagios debug: Found entry for Nagios::Hostgroup with name: linux
   [2015-08-17T21:29:22+00:00] DEBUG: Nagios debug: Creating entry for Nagios::Command with name: system-load!15
   [2015-08-17T21:29:22+00:00] DEBUG: Nagios debug: Creating entry for Nagios::Command with name: 10
   [2015-08-17T21:29:22+00:00] DEBUG: Nagios debug: Creating entry for Nagios::Command with name: 5!30
   [2015-08-17T21:29:22+00:00] DEBUG: Nagios debug: Creating entry for Nagios::Command with name: 25
   [2015-08-17T21:29:22+00:00] DEBUG: Nagios debug: Creating entry for Nagios::Command with name: 20
```

**Comment by sbotman** [comment]
While I admit that the behaviour is not correct, can you please explain what you are trying to achieve?
Because I'm wondering why you use 'system-load!15,10,5!30,25,20' as the command name.
This could be the command line that you want to execute, but I cannot find any command named like that.

**Comment by TheCase** [comment]
that is the check_command (with arguments) for that service.  I am not using that as a command name.  I updated my example recipe (added custom the nagios_command) above in hopes that it will clarify.

**Comment by sbotman** [comment]
Got it..... And that functionality indeed doesn't work at the moment.
I have not tested anything with this kind of format, so we will need to add that..

**Comment by sbotman** [comment]
What you can try in the meantime is escaping the ! and , with an \
That might do the trick...

**Comment by TheCase** [comment]
that was the first thing I thought to try :)  

Doesn't fix :(

**Comment by sbotman** [comment]
@TheCase can you try the branch: https://github.com/schubergphilis/nagios/tree/enable_service_arguments

I think that should fix your problem, but need to review the impact of this.
Also still need to write some tests for it, but did some local testing and seems to work fine.

Please let me know how this works out for you....

**Comment by sbotman** [comment]
While driving home I thought about this and think I made the wrong decision by adding the arguments to the command, while they should be part of the service. That would make more sense I think.. Will need to update the branch with that logic, but that I will do later tonight...

**Comment by TheCase** [comment]
yeah - that fixed it, and I'm still using the same options as listed in the first post.  

Thank you!

Still curious as to why the 'check_command' line is getting picked up as a nagios_command without a command_line option:

in commands.cfg:

```
# Skipping system-load because command_line is missing.
```

**Comment by sbotman** [comment]
I have updated the branch. Can you test again because I think this will also fix your missing line as here above.
Did a force push so you will need to delete your branch and fetch it again..

Only have the problem that if you don't specify the command separately and define everything within the service, that it will break the nagios config because the service name will be wrong. 
But fixing that will be the next step...

**Comment by sbotman** [comment]
On the other hand, this should be sufficient for now.
I was still thinking about something like this, for example you specify this within your cookbook:

```
nagios_service 'system-load!15,10,5!30,25,20' do
  options 'use'                 => 'default-service',
          'hostgroup_name'      => 'linux'
          'command_line'        => '$USER1$/check_load -w $ARG1$ -c $ARG2$'
end
```

With the current setup, this goes correct but your service name will contain illegal values.
But this will also work for stuff thats defined within databags....
So will need to parse this and replace the illegal values to _ or something.....
But then you will end-up with names that nobody wants any way.

So defining the command first like you do and then create the service, gives you the possibility to specify any kind of name you want. And this will look something like:

```
nagios_command 'system-load' do
  options 'command_line'    => '$USER1$/check_load -w $ARG1$ -c $ARG2$'
end

nagios_service 'system-high-load' do
  options 'check_command'       => 'system-load!20,15,10!40,35,30',
          'use'                 => 'default-service',
          'hostgroup_name'      => 'high_load_servers'
end

nagios_service 'system-medium-load' do
  options 'check_command'       => 'system-load!15,10,5!30,25,20',
          'use'                 => 'default-service',
          'hostgroup_name'      => 'medium_load_servers'
end

NOTE This is just an example
```

And since this is also a bit more advanced, not a lot of people will use the feature I guess.
Next to that, chef is generating the config anyway, so not having the arguments option will not be that big of a deal I assume.

Will try to write some test for this, so that some variations will be tested. And if you want to help me out on this, please feel free to add some :)

Gr Sander

**Comment by sbotman** [comment]
@TheCase do you have any comments on this? And did you manage to test the updated branch?

**Comment by bryancasey-ht** [comment]
I haven't had time to test.  Hopefully some time this week.

**Comment by TheCase** [comment]
I haven't had time to test.  Maybe some time this week.

**Comment by TheCase** [comment]
made some time for this.  It is not working correctly.  Anything after the first bang in the check_command option is now truncated.  Your test stanzas above create the following in services.cfg:

```
define service {
  use                  default-service
  service_description  system-high-load
  hostgroup_name      high_load_servers
  check_command        system-load
}

define service {
  use                  default-service
  service_description  system-medium-load
  hostgroup_name      medium_load_servers
  check_command        system-load
}
```

**Comment by sbotman** [comment]
@TheCase thank you for the feedback, I will need to review why this goes wrong :(

**Comment by sbotman** [comment]
@TheCase I have fixed the problem and also added some test kitchen checks.
Can you test again please :)

**Comment by sbotman** [comment]
created PR #416 for this issue..

**Comment by TheCase** [comment]
yes - tests look good.  Thanks!
