### ISSUE TITLE
contacts are being rendered in templates.cfg instead of contacts.cfg

### ISSUE THREAD

**Issue by kplimack** [sous-chefs/nagios#415]
this should be rendering in contacts.cfg without the register 0 line.  shouldn't be a tempate.

define contact {
  name           Jake Plimack
  use            default-contact
  contact_name   kplimack
  contactgroups  admins,admins-sms
  email          /dev/null
  register       0
}

then the configcheck barfs that my user doesn't exist.

**Comment by sbotman** [comment]
It seems that you have given the contact a name, which indicates that you are creating a template. So the logic is correct and you only should remove the name attribute. This will fix your problem.
