### ISSUE TITLE
allow custom "make" for server_source recipe

### ISSUE THREAD

**Issue by TheCase** [sous-chefs/nagios#417]
It seems they have made the old red/black theme default again - and I liked the cleaner exfoliation UI.

I'd submit a PR, but I'm not sure if it is best to open it up to allow for any custom "make" addition or just add a new attribute for "exfoliation_ui" that adds "make install_exfoliation" to the source build/install command.

**Comment by sbotman** [comment]
I would go with the most configurable option and set your preferred option as default :wink:

**Comment by TheCase** [comment]
ok - I'll put together a PR for this.

**Comment by sbotman** [comment]
Merged
