### ISSUE TITLE
The version 7.2.0 of the Nagios cookbook breaks Apache

### ISSUE THREAD

**Issue by ovaistariq** [sous-chefs/nagios#420]
The following line was added to the nagios::apache recipe which breaks apache on restart

```
include_recipe 'apache2::mpm_prefork' # mod_php5 is not threadsafe as packaged
```

The error is the following:
Starting httpd: httpd: Syntax error on line 106 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/mods-enabled/mpm_prefork.load: Cannot load /usr/lib64/httpd/modules/mod_mpm_prefork.so into server: /usr/lib64/httpd/modules/mod_mpm_prefork.so: cannot open shared object file: No such file or directory

**Comment by sbotman** [comment]
I personally don't use the apache configuration and use nginx, but it seems to me that you are missing the mpm module on disk. So I hope that you have a suggestion on how to fix this or maybe @ChrisLundquist can help with this as he suggested the change in PR #342

**Comment by ChrisLundquist** [comment]
Yeah, I agree the module doesn't seem to be installed. At the time I ran it `apache2::mpm_prefork` installed the needed packages.

I'm running Ubuntu 14.04.2, here are the relevant files

```
$ locate mpm
/etc/apache2/mods-available/mpm_event.conf
/etc/apache2/mods-available/mpm_event.load
/etc/apache2/mods-available/mpm_itk.load
/etc/apache2/mods-available/mpm_prefork.conf
/etc/apache2/mods-available/mpm_prefork.load
/etc/apache2/mods-available/mpm_worker.conf
/etc/apache2/mods-available/mpm_worker.load
/etc/apache2/mods-enabled/mpm_prefork.conf
/etc/apache2/mods-enabled/mpm_prefork.load
/usr/lib/apache2/module/disabled_by_admin/mpm_event
/usr/lib/apache2/module/enabled_by_admin/mpm_prefork
/usr/lib/apache2/modules/mod_mpm_event.so
/usr/lib/apache2/modules/mod_mpm_prefork.so
/usr/lib/apache2/modules/mod_mpm_worker.so
```

Here are the apache packages I have.

```
$ dpkg -l | grep apache
ii  apache2                          2.4.7-1ubuntu4.5                     amd64        Apache HTTP Server
ii  apache2-bin                      2.4.7-1ubuntu4.5                     amd64        Apache HTTP Server (binary files and modules)
ii  apache2-data                     2.4.7-1ubuntu4.5                     all          Apache HTTP Server (common files)
ii  libapache2-mod-php5              5.5.9+dfsg-1ubuntu4.11               amd64        server-side, HTML-embedded scripting language (Apache 2 module)
```

**Comment by ovaistariq** [comment]
On RHEL, at least, the mpm modules do not need to be installed separately.

**Comment by ovaistariq** [comment]
The prefork module is compiled in as can be seen below:

```
# httpd -l
Compiled in modules:
  core.c
  prefork.c
  http_core.c
  mod_so.c
```

```
# rpm -qi httpd
Name        : httpd                        Relocations: (not relocatable)
Version     : 2.2.15                            Vendor: CentOS
Release     : 29.el6.centos                 Build Date: Tue 13 Aug 2013 10:30:33 AM PDT
Install Date: Fri 14 Aug 2015 02:35:08 PM PDT      Build Host: c6b8.bsys.dev.centos.org
Group       : System Environment/Daemons    Source RPM: httpd-2.2.15-29.el6.centos.src.rpm
Size        : 3076447                          License: ASL 2.0
Signature   : RSA/SHA1, Tue 13 Aug 2013 10:32:39 AM PDT, Key ID 0946fca2c105b9de
Packager    : CentOS BuildSystem <http://bugs.centos.org>
URL         : http://httpd.apache.org/
Summary     : Apache HTTP Server
Description :
The Apache HTTP Server is a powerful, efficient, and extensible
web server.
```

**Comment by ChrisLundquist** [comment]
It sounds like the apache2 cookbook doesn't take this into account when it generates `/etc/apache2/mods-enabled/mpm_prefork.load` which sets the path to load the module

**Comment by ChrisLundquist** [comment]
It looks like there is an open issue https://github.com/svanzoest-cookbooks/apache2/issues/364

**Comment by svanzoest** [comment]
You do not want load a new MPM via the recipe, such as `include_recipe 'apache2::mpm_prefork'`, you will want to change the MPM via `node['apache']['mpm'] = 'prefork'`

**Comment by ovaistariq** [comment]
I have followed the logic of the apache2 cookbook and I agree that we do not want to include the mpm_prefork recipe, instead we should set the mpm attribute. I will file a PR.

**Comment by sbotman** [comment]
Thank you all for your support on this.... very much appreciated...
PR is merged so will close the ticket

**Comment by ovaistariq** [comment]
@sbotman when is the next release of the cookbook expected?

**Comment by sbotman** [comment]
I you want one, I will create one...

**Comment by ovaistariq** [comment]
@sbotman it would be nice to get a hot fix release for this particular fix, as the cookbook may be broken for users running it on CentOS/RHEL.

**Comment by sbotman** [comment]
agreed, will do..

**Comment by ovaistariq** [comment]
Thanks I appreciate it.

**Comment by sbotman** [comment]
Deploy is done and you're welcome, thanks for helping out...
