### ISSUE TITLE
The PagerDuty integration is broken

### ISSUE THREAD

**Issue by ovaistariq** [sous-chefs/nagios#421]
The nagios::pagerduty recipe does not add the pagerduty contacts to the "admins" contact group.

**Comment by sbotman** [comment]
You are correct and the big question is if it's needed.... The accounts that are created for pagerduty are Pseudo-Contacts, so don't know if these should be also admin. I will contact the people at pagerduty and ask for advice for this issue.

**Comment by ovaistariq** [comment]
Even if they are not added to the admins contact group, they would need to be added to one or more contact groups so that nagios can send alerts to them which will then be transformed into pages. Right?

**Comment by sbotman** [comment]
I tried to contact the peeps at pager-duty, but didn't got any response from them.
Did you manage to fix the issue in the meantime?

**Comment by ovaistariq** [comment]
@sbotman can you have a look at my PR. That basically allows the contact to be added to the admins group, meaning that every alert causes a page to be sent by PD.

**Comment by ovaistariq** [comment]
In my case I have different people in my team responding to different alerts by services, for example, network related pager goes to someone else, database related pager goes to someone else and so on and so forth.
To accomplish that I did the following:
- Create separate data bag items for database and network pagerduty contacts inside the nagios_pagerduty contact.
- Define a data bag item for network contact group inside nagios_contactgroups data bag and a separate item for database contact group
- Then for each service data bag item inside nagios_services I define the contact_groups based on who the service alert should be paging.

For example, nagios_services/mysql_service.json

``` json
{
  "id": "mysql_service",
  "description": "MySQL Service",
  "hostgroup_name": "mysql_servers",
  "contact_groups": "mysql",
  "command_line": "$USER1$/check_nrpe -t 60 -H $HOSTADDRESS$ -c check_mysql_alive"
}
```

Does the description of my implementation make sense?
