### ISSUE TITLE
unmanaged_hosts should also look at multi_environment_monitoring environment

### ISSUE THREAD

**Issue by lamroger** [sous-chefs/nagios#427]
https://github.com/schubergphilis/nagios/blob/master/recipes/_load_databag_config.rb#L146 
should look like
https://github.com/schubergphilis/nagios/blob/master/recipes/_load_databag_config.rb#L26
where it iterates through the allowed environments

**Comment by sbotman** [comment]
Code is merged, closing the ticket.
