### ISSUE TITLE
Loading unmanaged_hosts from data bag conditional is incorrect

### ISSUE THREAD

**Issue by lamroger** [sous-chefs/nagios#437]
https://github.com/schubergphilis/nagios/blob/master/recipes/_load_databag_config.rb#L146

I think it should be 
`next if item['environment'].nil? || item['environment'] != node.chef_environment`
instead of
`next unless item['environment'].nil? || item['environment'] == node.chef_environment`

If that sounds good, I can create a pr and write a test case.

**Comment by lamroger** [comment]
plus we might want to consider when `multi_environment_monitoring` is enabled

**Comment by lamroger** [comment]
Noted the multi_environement issue here already https://github.com/schubergphilis/nagios/issues/427
Forgot I already opened an issue for that

**Comment by sbotman** [comment]
You are right, this checking is indeed a bit strange and don't know what I was drinking when writing this ;)
If you create the PR, I will be more than happy to merge it for you...

**Comment by lamroger** [comment]
Looks like you're already on it! Thanks for maintaining and being so active! 
I blame Ruby's `unless` haha. I always have to double check

**Comment by sbotman** [comment]
I have merged my PR because I didn't get any comment on it :)
