### ISSUE TITLE
node['nagios']['interval_length'] should be node['nagios']['conf']['interval_length'] in the README

### ISSUE THREAD

**Issue by lamroger** [sous-chefs/nagios#439]
The attribute moved during one of the major updates and the README never got updated.

Side note: It was confusing when all conf attributes needed to be strings to be applied.

**Comment by lamroger** [comment]
Made a PR here.
https://github.com/schubergphilis/nagios/pull/440

**Comment by sbotman** [comment]
merged pr

**Comment by sbotman** [comment]
Think that we can also fix the string problem... created #441 for this..
