### ISSUE TITLE
Nagios  and apache use two different variables to set the timezone. 

### ISSUE THREAD

**Issue by timw077** [sous-chefs/nagios#443]
I'm not sure if there is a case where someone would want nagios to not use the same timezone as apache. 

attributes/config.rb:default['nagios']['conf']['use_timezone']                                = 'UTC'
attributes/default.rb:default['nagios']['timezone']      = 'UTC'

templates/default/apache2.conf.erb:  SetEnv TZ "<%= node['nagios']['timezone'] %>"

Since the node['nagios']['conf']['use_timezone'] is required for the special magic of the new nagios bits, I suggest changing the ERB to use the same attribute, and removing the redundant timezone attribute. 
Am I missing a 

templates/default/apache2.conf.erb:  SetEnv TZ "<%= node['nagios']['conf']['use_timezone'] %>"

**Comment by sbotman** [comment]
LGTM Tim! I would like to merge but would you be so kind and remove the version bump...

**Comment by timw077** [comment]
@sbotman done.

**Comment by sbotman** [comment]
Awesome!

I have deployed a new version yesterday and bumped the version for development. Guess more updates will follow and don't like to deploy a new version on a daily basis... 
Somewhere next week I would probably deploy a new version, so therefor my question :) 
So thank you for your support and fix! 

Cheers Sander

**Comment by sbotman** [comment]
merged
