### ISSUE TITLE
7.2.4 trips over nodes without any tags

### ISSUE THREAD

**Issue by jstange** [sous-chefs/nagios#453]
**recipes/_load_default_config.rb** assumes it's going to have a tags attribute, and throws a NoMethodError if any nodes in the land don't have tags:

```
# Pushing all nodes into the Nagios.instance model
nodes.each do |n|
   include = true
  nagios_array(n.tags).each do |tag|
    include = false if node['nagios']['exclude_tag_host'].include?(tag)
  end
  Nagios.instance.push(n) if include
end
```

You could stick a _rescue NoMethodError_ in there, I suppose. That's probably not the right thing, but it's what I just did to keep this thing from falling over on me.

**Comment by sbotman** [comment]
I see the problem, and I indeed made the assumption that all nodes have tags. Will fix...

**Comment by sbotman** [comment]
John, does this PR #456 work for you?

**Comment by sbotman** [comment]
@jstange can you review/retest this and share your comments?

**Comment by jstange** [comment]
No joy. `n.tags` is undefined under these circumstances, not empty, so you'll get roughly the same result:

```
NoMethodError
-------------
undefined method `any?' for nil:NilClass
```

**Comment by sbotman** [comment]
Well that's strange, node objects should always respond to 'tags'.
And the nagios_array function should always return something that's not nil.
So I don't understand why you get this NilClass error with...

I just updated the PR, can you test this one for me?

**Comment by sbotman** [comment]
@jstange, the current fix within master should solve the problem. Will close the issue for now, but feel free to reopen if you still experience issues with this.

**Comment by jstange** [comment]
Looks good. Thanks!
