### ISSUE TITLE
merge in latest code.. error in array

### ISSUE THREAD

**Issue by blueharford** [sous-chefs/nagios#464]
NoMethodError

---

  No resource or method named `nagios_array' for`Chef::Recipe "nagios_nodes"'

   31:  
   32:  # Pushing current node to prevent empty hosts.cfg
   33:  Nagios.instance.push(node)
   34:  
   35:  # Pushing all nodes into the Nagios.instance model
   36:  nodes.each do |n|
   37:    include = true
   38>>   nagios_array(n.tags).each do |tag|
   39:      include = false if node['nagios']['exclude_tag_host'].include?(tag)
   40:    end
   41:    Nagios.instance.push(n) if include
   42:  end
   43:  
   44:  # 24x7 timeperiod
   45:  nagios_timeperiod '24x7' do
   46:    options 'alias' => '24 Hours A Day, 7 Days A Week',
   47:            'times' => { 'sunday'    => '00:00-24:00',

**Comment by sbotman** [comment]
Looks like your merge is not correct: https://github.com/schubergphilis/nagios/blob/master/libraries/default.rb#L36

Please clone the project again and should be fixed

**Comment by blueharford** [comment]
its there in my library 

def nagios_array(exp)
  return [] if exp.nil?
  case exp
  when Array
    exp
  when String
    [exp]
  end
end

**Comment by sbotman** [comment]
it must be merging some cookbooks while uploading or something. You also have this code on the disk in the cache directory of chef?

**Comment by sbotman** [comment]
let's chat on gitter if you still have problems with this...
