### ISSUE TITLE
Nagios 4.x

### ISSUE THREAD

**Issue by joshskains** [sous-chefs/nagios#465]
Are there plans to support this?

**Comment by sbotman** [comment]
4.x should work fine.. Are you running into problems with 4.x?

**Comment by joshskains** [comment]
I haven't even tried. All the defaults, including paths, etc. go to "nagios3". We are running on 3.5.1 because of the defaults, but have been asked about 4.x. Do I just need to change a version number in a role?

**Comment by joshskains** [comment]
mcp@scripts-vp01a ~/wgu/chef-repo/cookbooks/nagios/attributes $ cat default.rb | grep source
  default['nagios']['resource_dir']  = '/etc/nagios'
  default['nagios']['resource_dir']  = '/etc/nagios3'
  # install via source on RHEL releases less than 6, otherwise use packages
    default['nagios']['server']['install_method'] = 'source'
  default['nagios']['server']['install_method'] = 'source'

# for server from source installation

default['nagios']['server']['url']       = 'http://iweb.dl.sourceforge.net/project/nagios/nagios-4.x/nagios-4.0.8/nagios-4.0.8.tar.gz'

# attribute to add commands to source build

default['nagios']['source']['add_build_commands'] = ['make install-exfoliation']
mcp@scripts-vp01a ~/wgu/chef-repo/cookbooks/nagios/attributes $ 

So weird. It defaults to this URL, but still installs 3.5.1....

**Comment by joshskains** [comment]
So I deleted /usr/sbin/nagios and allowed Chef to recompile. Hopefully that will work.

**Comment by joshskains** [comment]
Worked doing that.

**Comment by cole-christensen** [comment]
Nagios 4.x on centos 7.x encountered several issues (centos 7 isn't listed as being supported, but I'd like it)

**Comment by damacus** [comment]
So this seems to "work" for now. I'm going to close this issue down. 

We'll be doing a bunch of refactoring and cleaning up lingering issues. Defaulting to the latest Nagios seems super sensible.
