### ISSUE TITLE
API Key is stored unencrypted

### ISSUE THREAD

**Issue by jldugger** [sous-chefs/nagios#467]
This cookbook's options for receiving PagerDuty API keys are attributes or unencrypted data bags, neither of which are considered sufficiently secure by our operations team. We need a way to provide the API key from an encrypted data bags without passing it through an attribute.

**Comment by sbotman** [comment]
Can you give an example of which API key are we talking about here?

**Comment by jldugger** [comment]
Yea, sorry. I'm specifically referring to the PagerDuty API key, as in 

https://github.com/schubergphilis/nagios/blob/master/recipes/pagerduty.rb#L119

**Comment by sbotman** [comment]
Oke, two ways to solve this... 

One, we fix the cookbook code...

Two, you create a wrapper cookbook, depend on the nagios cookbook and in your cookbook recipe you do:

```
include_recipe 'nagios::default'
include_recipe 'nagios::pagerduty'

secret = (read the encrypted databag secret)
# and this will update the key for the pagerduty user:
nagios_contact 'pagerduty' do
    options 'pager' => secret
end
```

So as you see, you can update / change any configuration item after loading the defaults by just specifying them and updating one of the fields.

**Comment by jldugger** [comment]
Indeed, our plan is to fix this locally with our wrapper cookbook, but also push to get this fixed upstream. The first step of getting this fixed upstream is to make sure upstream wants it fixed, and thus this issue. 

But thank you for pointing out that configuration items can be updated. I was expecting to use chef-rewind, but this is more elegant by far.

**Comment by damacus** [comment]
Yeah databags and the like are going to get refactored out when we rewrite using custom resources.

If you could provide input into secrets management using a resource driven model that would be *awesome*!

**Comment by wilb** [comment]
> Yeah databags and the like are going to get refactored out when we rewrite using custom resources.

Is the intention to deprecate the use of the `nagios_*` databags for service check definition and all the other auto population mechanisms of this cookbook, or just for places where secrets are used?
