### ISSUE TITLE
exclude hostgroup in service

### ISSUE THREAD

**Issue by veilig2000** [sous-chefs/nagios#468]
I'm trying to exclude a hostgroup in a service from a databag.

```
{
    "id": "load",
    "hostgroup_name": "linux,!heartbeat",
    "command_line": "$USER1$/check_nrpe -H $HOSTADDRESS$ -c check_load"
}
```

I created the heartbeat hostgroup in a another databag and it exists in the hostgroups.cfg on my nagios server. When I try to exclude it w/ an exclamation mark in my service databag (see above), a new (empty) hostgroup is created in my hostgroups.cfg and then the service[reload] of chef complains about it.

```
define hostgroup {
  hostgroup_name  !heartbeat
}
```

Here's my error

```
 Checking host groups...
    Error: The name of hostgroup '!heartbeat' contains one or more illegal characters.
```

**Comment by dustyburwell** [comment]
I have this exact issue. Is there a way to do this?

**Comment by dustyburwell** [comment]
BTW, we're on the latest version of the cookbook.

It appears that the recipe is generating a entry in the hostgroups.cfg for each hostgroup included in the `hostgroup_name` attribute of the service, including ones that are intended to be negated like `!heartbeat`. Thus, you end up with an entry for a hostgroup named `!heartbeat`, and _that_ is what's failing.

I've spent a little bit of time trying to dig through and find what it is that's adding that hostgroup, but this cookbook has some abstractions that are making it difficult for me to parse. Hopefully the clues above will help someone with greater skills than I have to address this issue.

**Comment by tonymeng** [comment]
+1

**Comment by sbotman** [comment]
Hmm, seems that this is still active since @tonymeng +1 on this. One thing I don't understand is why would you want to exclude some group via the !, since you can just remove the group and have the same effect... Maybe I'm missing something here. Nevertheless we should try to fix this if it's an issue for 3 people..

**Comment by tonymeng** [comment]
Hi @sbotman , to shed some light on this, I'll talk about how we structure our roles in Chef.

We have a few hundred machines that all have different roles, however, each machine also has a `base` role. Inside nagios, we have checks for the `base` role including SSH, ping, disk_space, etc. However, when some of these checks fires, we want to route it specifically. So how we'd like to do that is.

``` ruby
nagios_command 'ping' do
  options 'command_line' => "path/to/plugin/check_ping -H $HOSTADDRESS$ -w 1000.0,80% -c 5000.0,100%"
end
nagios_service 'ping-base' do
  options 'hostgroup_name' => 'base,!a,!b',
          'check_command' => 'ping',
          'contacts' => 'email-base-group'
end
nagios_service 'ping-a' do
  options 'hostgroup_name' => 'a',
          'check_command' => 'ping',
          'contacts' => 'email-a-group'
end
nagios_service 'ping-b' do
  options 'hostgroup_name' => 'b',
          'check_command' => 'ping',
          'contacts' => 'email-b-group'
end
```

**Comment by sbotman** [comment]
Thank you for the info, needed this pointer. I get the idea now and makes sense..

**Comment by sbotman** [comment]
Somehow it looks that the latest version of this cookbook is doing something strange with the group membership. All groups don't have any members when I do a test run. Does anybody experience the same?

**Comment by tonymeng** [comment]
i'm on version 7.2.5 and the generation seems fine

**Comment by tonymeng** [comment]
fyi i think @sbotman is fixing this as well : https://github.com/schubergphilis/nagios/compare/develop#diff-5538e34ba8d6106723f552e70154d32bR300

**Comment by shoekstra** [comment]
@tonymeng when you say "generation seems fine", do you mean that this is no longer a problem or there is no problem generating a config file with a negated hostgroup name?

Is it possible to confirm if this issue still exists with the latest release in the supermarket?
