### ISSUE TITLE
Publish $USER$ values for /etc/nagios/resource.cfg from role or data bag

### ISSUE THREAD

**Issue by nkadel-skyhook** [sous-chefs/nagios#482]
The "$USER$" values normally deployed in /etc/nagios/resource.cfg can be very useful for keeping mysql or other passwords out of direct source control entries, or for other shared values which should not be directly in the command options. Is it feasible to activate a role based, or even encrypted data bag based, access to set these resources?

**Comment by sbotman** [comment]
You should be able to manage the resources within the resources.cfg via the nagios_resource provider.
Example:

```
my_secret = get_your_secret_key_from_anywhere

nagios_resource 'USER2' do
  options 'value' => my_secret
end
```

You should be able to use this anywhere, so also within your wrapper cookbook.
And then you can then use the $USER2$ anywhere you like, as for example as the password for mysql.

HTH
Sander

**Comment by sbotman** [comment]
I assume that I have answer the question so I will close the issue for the moment. Please feel free to reopen the issue if the suggestion is not solving your problem.

**Comment by nkadel-skyhook** [comment]
Sorry, I've been busy.

Thank you for the pointer, I'll test out the resources setting. Mind you, putting "secrets" in plain text rather than in an encrypted data bag is its own problem, but it's a common one for many chef cookbooks.
