### ISSUE TITLE
more detail/example needed to get going

### ISSUE THREAD

**Issue by Paul424** [sous-chefs/nagios#485]
If you're not familiar with Nagios (like myself) it's difficult to get going with these cookbooks (nagios+nrpe). For me it would really help to have a small example to get basic monitoring counters included for a small cluster. With a small example working it;s much easier to scale up...

For example what is not clear now:
- when do i need nrpe? Where to install it? How do these connect to the server?
- what checks are provided by default? 

Thanks for any tips,
Paul

**Comment by sbotman** [comment]
Hi Paul,

It's indeed very hard to start with this cookbook while you don't have any experience with Nagios.
So I would start with the Nagios documentation on https://assets.nagios.com/downloads/nagioscore/docs/nrpe/NRPE.pdf

But I will try to answer your questions:
NRPE client is used to execute scripts/executables that check something and report this back to nagios.
NRPE client is installed on the target machine were you want to run the check.
Nagios uses check_nrpe with some parameters to connect to the NRPE client
The default checks are installed under /usr/lib/nagios/plugins/\* so here you can find them.

HTH Sander

**Comment by ikrauchanka** [comment]
Hello Paul,
I agree with Sander. Try to install and configure nagios manually, without cookbook. Once you get familiar with nagios internals, you will be ready to dive into cookbook. Without nagios engine knowledge you will not be able fix an issue in nagios once bad things happen.
