### ISSUE TITLE
interval math issue

### ISSUE THREAD

**Issue by TheCase** [sous-chefs/nagios#486]
I think this whole interval/seconds thing needs to be reevaluated.

In this logic recently introduced to libraries/default.rb:

```
interval = seconds
  if node['nagios']['conf']['interval_length'].to_i != 1
    interval = seconds.to_f / node['nagios']['conf']['interval_length']
  end
  interval
```

I used to have my interval_length set to 60 (seconds), which meant that I could define things like check_interval and retry_interval in minutes rather than seconds (ie. 5 vs 300).

What this new logic actually does is some wacky math that makes zero sense (to me at least):

if I have my interval_length set at 60 (seconds), which should logically make nagios interpret all intervals as minutes rather than seconds.  Instead it takes my "check_interval" of 5 (what is supposed to be minutes) and divides it by 60 (interval_length), with a final value of 0.0833333333333 of the check_interval of 60 seconds.  This makes my intended 5 minute interval convert to ~5 seconds.

The only case where this logic actually works as intended is if you set the interval_length to 1 and use seconds for the interval values.  If so, why make interval_length a configurable attribute at all?

This conversion needs to be removed for the interval_length value to work as designed in nagios.

I'll put together a PR as soon as I find the time.

**Comment by sbotman** [comment]
I have to admit that this problem/issue is created by me because I tried to figure out the logic behind it but it never made any sense to me. So my idea was to specify all intervals in seconds when it comes to configuration. And that's why I have put the default value of the nagios_conf_interval_length to 1.
So if you change the interval to 60, we will need to divide the seconds with the interval, but then you should not change the config! so 300 / 60 = 5. With this the logic will work (and I guess this is the point where I went wrong), but if you change the config settings then you will get indeed wrong values.

I'm open for any suggestion that you have, but I guess we should make it clear (something I should have done already!) what the new logic/reasoning behind the config settings is. 

So thank you for raising the question and your corporation on this, because I was kinda lost here...
Kind Regards, Sander

**Comment by explody** [comment]
I'm curious why nagios_interval() exists at all, you do not need to convert time between "units" seconds or minutes.  I grant that it can be confusing but the docs are pretty direct.  

Here is interval length (_always_ seconds)

```
Format: interval_length=<seconds>
Example:    interval_length=60
This is the number of seconds per "unit interval" used for timing in the scheduling queue, re-notifications, etc. "Units intervals" are used in the object configuration file to determine how often to run a service check, how often to re-notify a contact, etc.
```

And here is check_interval

```
This directive is used to define the number of "time units" between regularly scheduled checks of the host. Unless you've changed the interval_length directive from the default value of 60, this number will mean minutes. More information on this value can be found in the check scheduling documentation.
```

And here's the snip for command_check_interval

```
Format: command_check_interval=<xxx>[s]
Example:    command_check_interval=1
If you specify a number with an "s" appended to it (i.e. 30s), this is the number of seconds to wait between external command checks. If you leave off the "s", this is the number of "time units" to wait between external command checks. Unless you've changed the interval_length value (as defined below) from the default value of 60, this number will mean minutes.

```

Some examples:

```
# interval_length # unset, defaults to '60'. This is one 'time unit'
check_interval = 1   # Nagios interprets this as 1 'time unit' or 60 seconds
command_check_interval = 120s # with the trailing 's', nagios interprets this as 120 seconds
```

```
interval_length = 120 # This is one 'time unit'
check_interval = 1   # Nagios interprets this as 1 'time unit' or 120 seconds, as defined by interval_length
command_check_interval = 1 # Nagios interprets this as 1 'time unit' or 120 seconds, as defined by interval_length
```

Point being for both, you do not need to interpolate any intervals into seconds for Nagios, it does it for you.  It's up to the user setting the config variables to ensure the multipliers work the way they want.  

As the time is calculated now, it utterly breaks Nagios (my check intervals ended up being 0.016666666666666666 seconds, which drove the system load up to 50 and nearly killed the VM).  Our inelegant fix was to neutralize nagios_interval() completely:

``` ruby
def nagios_interval(seconds)
  if seconds.to_i == 0
    fail ArgumentError, 'Specified nagios interval of 0 seconds is not allowed'
  end
  seconds
end
```
