### ISSUE TITLE
Put distinct types of template in distinct config files

### ISSUE THREAD

**Issue by nkadel-skyhook** [sous-chefs/nagios#491]
The merging of contact, host, and service templates into a single file is confusing. This is aggravated by having distinct nagios_templates, nagios_hosttemplates, They should ideally be split to three distinct files for maximum comprehensibility and correspondence with the original data bags.

**Comment by TheCase** [comment]
IMO it shouldn't matter.  If your wrapper passes spec tests, who cares how the config stanza are broken up?

**Comment by nkadel-skyhook** [comment]
Anyone trying to draw links between the data bags they write, and the resulting configuration files the data resides in, can be confused by the inconsistency. This is actually a longstanding problem with the original default published nagios "templates.cfg", and this is a good opportunity to eliminate the confusion.

If it's welcome, I'd be happy to submit patches for it.

**Comment by sbotman** [comment]
I personally don't care, so feel free to move the configuration into another file as you want.

**Comment by damacus** [comment]
@nkadel-skyhook a pr would be great. 

I'm going to start a custom resource rewrite and we'll look at doing it exactly this way for simplicity.

**Comment by shoekstra** [comment]
Hi @nkadel-skyhook,

You're welcome to submit a PR to add this functionality but for most people when a configuration file is managed by Chef they aren't too phased what it looks like because the config is in their config management system.

I'm going to close this for now, again PR welcome if you wish to tidy up the files.

Stephen
