### ISSUE TITLE
nagios service hwo to  setting don't send to some contacts or congtactgroup

### ISSUE THREAD

**Issue by mjesse88** [sous-chefs/nagios#494]
I first define service template 
define service{ 
name fortex_win_service ; The name of this service template 
use generic-service ; Inherit default values from the generic-service definition .
.............................. 
contact_groups contactgroup01，contactgroup02
 ......................... ; 
register 0
}

second I define servervice01 belong to host01,host02 
define service{ use fortex_win_service 
host_name host01,host02 
service_description servervice01 
check_command check_nrpe_remote!CheckCPU!"warn=load>70%" "crit=load>90%" time=5m ; 
} 
The email send to contactgroup01，contactgroup02

Now I wan to service01 belong to host 03,but the email onley send to contactgroup01, don't send to contacgroup02.what to setting it. 
Thank you veary much.

**Comment by TheCase** [comment]
Anything you set explicitly under a service will override the setting from a template

**Comment by mjesse88** [comment]
Hi TheCase,
thanks for your respone.
I fixed this problem .
hostname and Ip are  primary key of nagios host.
