### ISSUE TITLE
"service_template" field in "nagios_services" data bag item is not being configured in services.cfg

### ISSUE THREAD

**Issue by wilb** [sous-chefs/nagios#495]
It looks like there is a regression in the parsing of the nagios_services data bag - I've just realised that some logfile checks I have defined are just using the default-service template rather than the default-logifle configured in the data bag item.

`$ knife data bag show nagios_services chef-client_error`

`command_line:        $USER1$/check_nrpe -H $HOSTADDRESS$ -c chef-client_error -t 30`
`hostgroup_name:      linux`
`id:                  chef-client_error`
`notification_period: extended-hours`
`service_template:    default-logfile`

On the Nagios in services.cfg.erb this gets parsed as:

`define service {`
`use                  default-service`
`service_description  chef-client_error`
`hostgroup_name       linux`
`check_command        check_chef-client_error`
`notification_period  extended-hours`
`}`

---

On an older host (nagios 5.2.1 cookbook) with a similar configuration I see:

`$ knife data bag show nagios_services chef-client_error` 

`command_line:        $USER1$/check_nrpe -H $HOSTADDRESS$ -c chef-client_error -t 30`
`hostgroup_name:      linux`
`id:                  chef-client_error`
`notification_period: office-hours`
`service_template:    default-logfile`

`define service {`
`service_description chef-client_error`
`hostgroup_name linux`
`check_command check_chef-client_error`
`use default-logfile`
`notification_period office-hours`
`}`

**Comment by wilb** [comment]
Having stepped through the code this looks like a documentation issue. The field is now actually just called "use" in line with how the Nagios configuration ultimately gets rendered, as can be seen here:

https://github.com/schubergphilis/nagios/blob/d58eb45bd6bcb174076917758026b791916c730c/libraries/service.rb#L404

The data bag documentation still refers to "service_template" though:

https://github.com/schubergphilis/nagios/wiki/services

**Comment by sbotman** [comment]
should be fixed on the develop branch.

**Comment by shoekstra** [comment]
This should be fixed in the latest release to the supermarket; please reopen if still having a problem.
