### ISSUE TITLE
hostgroup_members in hostgroup is not being generated

### ISSUE THREAD

**Issue by tonymeng** [sous-chefs/nagios#501]
When trying to create a nagios hostgroup using sub-hostgroups via `hostgroup_members`, the hostgroup is generated as an empty hostgroup

``` ruby
nagios_hostgroup `a` do
    options 'hostgroup_members' => 'x,y,z'
end
```

generates

```
define hostgroup {
  hostgroup_name a
}
```

but should generate

```
define hostgroup {
  hostgroup_name a
  hostgroup_members x,y,z
}
```

**Comment by sbotman** [comment]
Hi @tonymeng, can you checkout the develop branch for me and let me know if this fixes your issues. (ps needs more refinement but it's a start)

**Comment by tonymeng** [comment]
i tried running with your changes (on nagios 4.0.8, not 4.2.1). and there were no hostgroups generated when only hostgroup_members was set in `nagios_hostgroup`. do I need to update nagios for this to work?

**Comment by sbotman** [comment]
No, the version of nagios is not related to the configuration. So that should not have any impact.
Let me add some testing for the hostgroups.

**Comment by sbotman** [comment]
Phfff, seems that it's a typo bug... Nice find @tonymeng.... updated the develop branch for the moment.

**Comment by tonymeng** [comment]
great thanks. I'll give it a shot later and let you know.

**Comment by tonymeng** [comment]
lgtm! thanks @sbotman

**Comment by tonymeng** [comment]
ill let you close it when you merge it :)

**Comment by tonymeng** [comment]
thoughts on when this will be released?

**Comment by sbotman** [comment]
I'm quite busy at the moment and will have to do this in my spare time. Maybe I can ask @snkutlu to take over, but I'm sure he is also very busy (if not let me know :) )

**Comment by tonymeng** [comment]
bump

**Comment by tonymeng** [comment]
it's almost been a year, any updates on when this will be merged? the fix works in prod just a hassle changing the cookbook every time.

**Comment by shoekstra** [comment]
@tonymeng will take a look and see if we can get this released in next day or two.

**Comment by tonymeng** [comment]
thanks!

**Comment by tonymeng** [comment]
was this released?

**Comment by shoekstra** [comment]
This should be fixed in the latest release to the supermarket; please reopen if still having a problem.
