### ISSUE TITLE
nagios_hostgroups fails unless monitored_environments is set

### ISSUE THREAD

**Issue by ezray** [sous-chefs/nagios#502]
The documentation specifies that if `multi_environment_monitoring` is true, `monitored_environments` defaults to [], meaning all environments are monitored. However, if `monitored_environments` isn't set, attempting to use a nagios_hostgroups data bag fails with a `400 "Bad Request"` error. The cause appears to be that in `recipes/_load_databag_config.rb`, `node['nagios']['monitored_environments']` is used without first checking to see if it's been defined.

**Comment by wilb** [comment]
:+1: - encountered this myself.

**Comment by wilb** [comment]
Just to revisit this, setting `node['nagios']['monitored_environments'] = [ "*" ]` results in the search populating all environments withing the Chef organisation as per the documentation. Maybe the simplest fix is to update the default attribute within the cookbook to contain the wildcard?

**Comment by wilb** [comment]
Unfortunately doing the above causes unintended consequences with the unmanagedhosts data bag; environment is evaluated before the chef search has taken place so any checks that are set to be active in only certain environments will not be active at all.

**Comment by NZenitram** [comment]
Where can I find some more discussion on this issue? It still occurs and I am having a hard time finding a work around.
