### ISSUE TITLE
default['nagios']['server']['src_dir'] logic is broken 

### ISSUE THREAD

**Issue by wilb** [sous-chefs/nagios#505]
The following attribute is evaluated at compile time which results in it always being '4.0.8' even when you override node['nagios']['server']['url']

`default['nagios']['server']['src_dir']   = node['nagios']['server']['url'].split('/')[-1].chomp('.tar.gz')`

(from https://github.com/schubergphilis/nagios/blob/master/attributes/default.rb )

This  results in the compilation phase being attempted from the `nagios-4.0.8` directory which doesn't exist.

```
   ---- Begin output of "bash"  "/tmp/chef-script20161019-13204-8ge0o0" ----
   STDOUT: 
   STDERR: /tmp/chef-script20161019-13204-8ge0o0: line 1: cd: nagios-4.0.8: No such file or directory
   /tmp/chef-script20161019-13204-8ge0o0: line 2: ./configure: No such file or directory
```

**Comment by damacus** [comment]
Oh good lord. Yeah, so I'm thinking about doing a custom resource rewrite for this. 

And this is exactly why. Compile time attributes and attribute driven application cookbooks in general are a pain to work with.

**Comment by damacus** [comment]
I'm putting wont fix on this. But we will fix this behaviour as part of the rewrite (i.e. this issue should be invalid!)
