### ISSUE TITLE
default['nagios']['conf']['check_result_path'] not created as part of source install

### ISSUE THREAD

**Issue by wilb** [sous-chefs/nagios#506]
Just completed a source install of 4.2.1 on CentOS 7 and the converge ultimately fails with Nagios not starting up due to `/var/log/nagios/spool/checkresults` not being present. This gets rendered out to config via:

default['nagios']['conf']['check_result_path'] = "#{node['nagios']['state_dir']}/spool/checkresults"

Nagios starts up OK once the directory is created. `/var/log/nagios/spool` and `/var/log/nagios/spool/checkresults` should be `nagios:nagios` 0750.

**Comment by seren** [comment]
We're running into this issue as well. Pre-creating the directory doesn't work since it needs to be owned by the nagios user which doesn't exist yet. This is with recipe version 7.2.4.

**Comment by shoekstra** [comment]
Hi!

We are tracking/fixing this via #534.  Once the OpenSuse support has been fixed we'll merge this in and cut a new release.  Should happen in next day or so.

Cheers,
Stephen

**Comment by shoekstra** [comment]
This should be fixed in the latest release to the supermarket; please reopen if still having a problem.
