### ISSUE TITLE
Use of deprecated nginx cookbook

### ISSUE THREAD

**Issue by GitBytes** [sous-chefs/nagios#512]
Hey @sbotman,

I just wanted to bring up some dependency issues..

I was attempting to bump up some dependencies in our infrastructure and discovered the `nagios` cookbook depending on the `nginx` cookbook which is in the process of being deprecated and/or rewritten (See [`nginx`](https://supermarket.chef.io/cookbooks/nginx) cookbook and [`chef_nginx` ](https://supermarket.chef.io/cookbooks/chef_nginx) cookbook). Sorry, not too sure where things are headed there.. Point being, the current version of the `nginx` cookbook on the supermarket, `2.7.6`, is depending on some pretty old versions of `yum-centos` and `ohai`. Is there a plan to either migrate from the `nginx` cookbook to `chef_nginx` or are you waiting for the `3.0.0` release of the `nginx` cookbook? It would be really nice to not have to rely on such old dependencies for `ohai`, `yum-centos` (by extension `yum`). I realize this would require some level of effort and planning of a new release in order to migrate if that is the plan but I wanted to check before I went through the effort to backport to older versions of these cookbooks to satisfy the soon to be deprecated `nginx` cookbook. Thanks so much in advance!

Best Regards,
GitBytes

**Comment by GitBytes** [comment]
@sbotman I see this may be possibly addressed in #510 and/or #509? Waiting to see if that maybe solves this. Thanks..

**Comment by tas50** [comment]
This has been merged to master now
