### ISSUE TITLE
RHEL7 RPMs have changed the 'state_dir'

### ISSUE THREAD

**Issue by wilb** [sous-chefs/nagios#515]
4.2 RPMs have recently been pushed up to EPEL, but the state_dir has changed which results in a failing converge. 

```
Mar 03 09:33:01 ebe36ef9caf3 nagios[1285]: Error in configuration file '/etc/nagios/nagios.cfg' - Line 56 (Check result path '/var/log/nagios/spool/checkresults' is not a valid directory)
Mar 03 09:33:01 ebe36ef9caf3 nagios[1285]: Error processing main config file!
```

In 4.0.x it was `/var/log/nagios`, it looks like the 4.2.x packages are now using `/var/spool/nagios`

Given some attributes are merged early in `attributes/config.rb` it doesn't look like a simple override of `node['nagios']'['state_dir']` actually fixes this, I'm just looking into it.

**Comment by damacus** [comment]
Thanks @wilb if you can figure out what's going on there. We'll happily pull in a fix.

**Comment by wilb** [comment]
It's a while since I raised this and I really can't remember whether I got to the bottom of it or not. Will check when I'm back in front of a RHEL box and report back.

**Comment by wilb** [comment]
Unfortunately I hacked around it with a symlink as we've still got a mix of 4.0.x and 4.2.x hosts in use. Will try and find time to fix it properly at some point.

**Comment by shoekstra** [comment]
This should be fixed in the latest release to the supermarket; please reopen if still having a problem.

Thanks,
Stephen
