### ISSUE TITLE
Accessing Nagios doesn't work

### ISSUE THREAD

**Issue by ghost** [sous-chefs/nagios#517]
### Cookbook version
7.2.6

### Chef-client version
12.19.36

### Platform Details
Ubuntu 14.04.5 LTS

### Scenario:
I'm trying to access the nagios web interface

### Steps to Reproduce:
I just followed the instruction.
I created a monitoring role with the following cookbooks (in that order)

1. munin::server
2. munin::server_nginx
3. nagios::nginx
4. nagios
5. nrpe

In addtion I created a Data Bag called "nagios_services" with a ssh check
```
{
  "id": "ssh",
  "hostgroup_name": "linux",
  "command_line": "$USER1$/check_ssh $HOSTADDRESS$"
}
```

### Expected Result:
Since I just did pure basic configuration I hoped to see the usual nagios interface

### Actual Result:
Instead of seeing the nagios interface I just keep downloading a not further named page.

I'm not sure if this is an actual bug, but I don't know where I went wrong.

**Comment by shoekstra** [comment]
This should be fixed in the latest release to the supermarket; please reopen if still having a problem.
