### ISSUE TITLE
Remove sever manually

### ISSUE THREAD

**Issue by lam0re** [sous-chefs/nagios#518]
### Cookbook version
7.2.6

### Chef-client version
12.8.1

### Platform Details
Ubuntu 14.04

### Scenario:
I created a node with the nrpe cookbook. I deleted that node and recreated it but without the nrpe cookbook. The node is still in my Nagios hosts list but now there is no nrpe, so all tests fail. Can I remove that host from Nagios somehow manually?

**Comment by shoekstra** [comment]
@lam0re did you delete your server from Chef?

This cookbook uses search to populate it's monitored hosts list.  To delete the client from the server you can do:

```
knife node delete <node name>
knife client delete <client name>
```

Please could confirm if this fixes your host appearing in the Nagios host list.

Stephen
