### ISSUE TITLE
Question: Has this been abandoned?

### ISSUE THREAD

**Issue by awworrell** [sous-chefs/nagios#519]
### Cookbook version
7.2.6

### Platform Details
Ubuntu 12.04 +

### Scenario:
Has this project been abandoned? I am having issues with dependencies where nginx is not being updated thus giving older versions of build-essentials and 7-zip. 7-zip has been deprecated and moved to a new project. The same can be said for nginx.

**Comment by sbotman** [comment]
Well not really, just haven't got much time lately to work on this. But please feel free to should in any PR if needed.

**Comment by awworrell** [comment]
I was looking into the metadata file and it looks like the dependency has been updated already to include chef_nginx. Has a release been done recently into the chef supermarket?

**Comment by robbat2** [comment]
`nginx_simplecgi` seems to abandoned upstream, and still pulls in the old `nginx` cookbook, so you end up with conflicting resource names between `nginx` and `nginx_simplecgi` :-(.

**Comment by damacus** [comment]
Not anymore! 

Thanks for your interest. We've recently moved the cookbook to Sous-Chefs and are looking for active maintainers and contributors. If this you please drop by the [chef community slack, #sous-chefs room ](https://chefcommunity.slack.com/archives/sous-chefs)

**Comment by damacus** [comment]
@robbat2 thanks for pointing that out. I'm going to start assigning issues to these bugs. Some of which need to go into the [main chef_nginx cookbook](https://github.com/chef-cookbooks/chef_nginx) probably
