### ISSUE TITLE
nginx_simplecgi looks abandoned

### ISSUE THREAD

**Issue by damacus** [sous-chefs/nagios#525]
`nginx_simplecgi` seems to abandoned upstream, and still pulls in the old nginx cookbook, so you end up with conflicting resource names between nginx and nginx_simplecgi :-(.

**Comment by damacus** [comment]
As per @rodriguezsergio in #519

**Comment by finchr** [comment]
I'm also getting the following error with this cookbook on Ubuntu 16.04: 

       Recipe: nginx_simplecgi::php
         * apt_package[php5-cgi] action install
           * No candidate version available for php5-cgi
           ================================================================================
           Error executing action `install` on resource 'apt_package[php5-cgi]'
           ================================================================================
           
           Chef::Exceptions::Package
           -------------------------
           No candidate version available for php5-cgi
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/nginx_simplecgi/recipes/php.rb
           
            29:   package package_name
            30: end

**Comment by damacus** [comment]
@finchr that's actually a system/apt package error you're getting there rather than a cookbook cookbook dependency issue. 

Seeing as it's php5, I'm not at all surprised. If you'd like to help update this cookbook to the latest Nagios version that'd be great!

**Comment by finchr** [comment]
Hi Dan,


I would be more than happy to help update the cookbook! I've had to make a few fixes to get this working on Ubuntu 16.04 and would be glad to share the changes.

**Comment by finchr** [comment]
What is the current status of the cookbook? I can't get anything to converge due to problems with the data in test/integration/data_bags. I can force the convergence by modifying (i.e. deleting) the data bags but then the kitchen verify steps fail.

**Comment by damacus** [comment]
I'm working on this https://github.com/sous-chefs/nagios/pull/528

Amongst a few other PRs in other sous-chefs repos (ruby_rbenv being one) 

If you feel like you're able to contribute to that PR, that would be great!

**Comment by finchr** [comment]
I'll take a look at that as well, I'll send you a pull request if I make any progress on it.

**Comment by sirosen** [comment]
I'm running into issues with this in my environment because `chef_nginx` currently requires `ohai >= 4.1.0` and `nginx` requires `ohai ~> 2.0`.

This cookbook's dependency on `nginx_simplecgi` is therefore blocking me from upgrading to the latest version.

**Comment by finchr** [comment]
Hi @sirosen, I have pull request in (#530) which will fix this.

**Comment by sirosen** [comment]
#530 is merged, but didn't include a `closes` or `resolves` for GitHub to parse.
Could someone manually close this?

**Comment by tas50** [comment]
I'm closing this out since I'm now the owner of nginx_simplecgi and we've also moved away from the cookbook.
