### ISSUE TITLE
apache2::mod_php5 no longer present in v4.0.0 of apache2 cookbook 

### ISSUE THREAD

**Issue by wilb** [sous-chefs/nagios#535]
Another bug without a PR to fix it I'm afraid, but just so it's tracked for now a new version of the apache2 cookbook was released yesterday which has removed the mod_php5 recipe in favour of one called mod_php.

Currently https://github.com/sous-chefs/nagios/blob/master/recipes/apache.rb#L21 includes mod_php5 - presumably a straight swap should fix it but I haven't actually tested it yet.

**Comment by tas50** [comment]
Fixed by https://github.com/sous-chefs/nagios/pull/537

Thanks for the report
