### ISSUE TITLE
It would be nice to be able to use custom SSL cipher settings with apache

### ISSUE THREAD

**Issue by craigjamesstewart** [sous-chefs/nagios#536]
I created a pull request sometime ago to add this feature. It's a fairly simple pull request. #529 

I haven't pressed for this as it's a nice to have, but it would be a useful feature enhancment, and given the pace at which old SSL ciphers are being deprecated these days, and the number of practical vulnerabilities being found in weak ciphers, I'm sure I'm not the only one that would like this feature.

**Comment by tas50** [comment]
I merged the PR. Thanks
