### ISSUE TITLE
apache2 cookbook version dependency

### ISSUE THREAD

**Issue by agonzalez-tk** [sous-chefs/nagios#543]
### Cookbook version
7.2.7

### Chef-client version
12.x

### Scenario:
nagios cookbook depend on apache2, most recent changes on apache2(4.0,5.0) cookbook removed recipies mod_php5

**Comment by shoekstra** [comment]
Hi!

This is true - we updated [recipes/apache.rb](include_recipe 'apache2::mod_php'
) to reflect this but I see we missed the dependency in the `metadata.rb`.

Thanks for reporting!
