### ISSUE TITLE
Error executing action `create` on resource 'template[/etc/apache2/sites-available/nagios3.conf]'

### ISSUE THREAD

**Issue by ghost** [sous-chefs/nagios#545]
### Cookbook version
7.2.7

### Chef-client version
chef-client version: 13.2.20

### Platform Details
UBuntu 16.04

### Scenario:
Install Nagios

  Error executing action `create` on resource 'template[/etc/apache2/sites-available/nagios3.conf]'
==> default:     ================================================================================
==> default:
==> default:     Chef::Mixin::Template::TemplateError
==> default:     ------------------------------------
==> default:     undefined method `platform_family' for #<Chef::Node::Attribute:0x0000000391c708>
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/nagios/recipes/apache.rb
==> default:
==> default:      30: template "#{node['apache']['dir']}/sites-available/#{node['nagios']['server']['vname']}.conf" do
==> default:      31:   source 'apache2.conf.erb'
==> default:      32:   mode '0644'
==> default:      33:   variables(
==> default:      34:     nagios_url: node['nagios']['url'],
==> default:      35:     https: node['nagios']['enable_ssl'],
==> default:      36:     ssl_cert_file: node['nagios']['ssl_cert_file'],
==> default:      37:     ssl_cert_key: node['nagios']['ssl_cert_key']
==> default:      38:   )
==> default:      39:   if File.symlink?("#{node['apache']['dir']}/sites-enabled/#{node['nagios']['server']['vname']}.conf")
==> default:      40:     notifies :reload, 'service[apache2]'
==> default:      41:   end
==> default:      42: end
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/nagios/recipes/apache.rb:30:in `from_file'
==> default:
==> default:     template("/etc/apache2/sites-available/nagios3.conf") do
==> default:       action [:create]
==> default:       default_guard_interpreter :default
==> default:       source "apache2.conf.erb"
==> default:       variables {:nagios_url=>nil, :https=>false, :ssl_cert_file=>"/etc/nagios3/certificates/nagios-server.pem", :ssl_cert_key=>"/etc/nagios3/certificates/nagios-server.pem"}
==> default:       declared_type :template
==> default:       cookbook_name "nagios"
==> default:       recipe_name "apache"
==> default:       mode "0644"
==> default:       owner nil
==> default:       group nil
==> default:       path "/etc/apache2/sites-available/nagios3.conf"
==> default:       verifications []
==> default:     end

------------------------------------------------------------------------------------
The Fix
------------------------------------------------------------------------------------
Changed line 21 in the apache.conf.erb file from this:
<% if node.platform_family == 'debian' && node['nagios']['server']['install_method'] == 'package'-%>

to this:

<% if node['platform_family'] == 'debian' && node['nagios']['server']['install_method'] == 'package'-%>

And the problem is fixed.

**Comment by shoekstra** [comment]
Hi!

Thanks for reporting, it looks like this problem has already been solved but it has not being pushed to the supermarket yet, will make sure this happens in the next day or.

Stephen

**Comment by shoekstra** [comment]
This should be fixed in the latest release to the supermarket; please reopen if still having a problem.
