### ISSUE TITLE
server_source recipe calls nonexistent php recipe

### ISSUE THREAD

**Issue by mclyde-oracle** [sous-chefs/nagios#568]
### Cookbook version
8.0.0

### Chef-client version
14.0.202

### Platform Details
Oracle Linux 7.5

### Scenario:
Allow chef-client to complete when using server_source

### Steps to Reproduce:
I am calling the server_source recipe, which includes php::module_gd. That recipe no longer exists in recent versions of the php cookbook.

### Expected Result:
chef-client will fail

**Comment by tas50** [comment]
Fixed in 8.1. Thanks for the  PR
