### ISSUE TITLE
Problem with hostgroups

### ISSUE THREAD

**Issue by tamwoza** [sous-chefs/nagios#615]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

Unable to resolve a group of groups using hostgroup_members

## :pancakes: Cookbook version

8.0.0

## :woman_cook:  Chef-Infra Version

12.20.3

## :tophat: Platform details

RHEL 6.10

## Steps To Reproduce

Added the following code to my cookbook:

nagios_hostgroup 'foo' do
  options 'alias' => 'foo',
               'hostgroup_members' => 'foo1, foo2'
end

Added the following code to my databags:

{
  "id": "foo1",
  "hostgroup_name": "foo1",
  "search_query": "name:server1"
}

{
  "id": "foo2",
  "hostgroup_name": "foo2",
  "search_query": "name:server2"
}
## :police_car: Expected behavior

I expected to see the following in the hostgroups.cfg file that gets generated:

define hostgroup {
  hostgroup_name  foo
  alias foo
  hostgroup_members         foo1,foo2
}

define hostgroup {
  hostgroup_name  foo1
  members         server1
}

define hostgroup {
  hostgroup_name  foo2
  members         server2
}

Instead, I am getting the following:

define hostgroup {
  hostgroup_name  foo
  alias foo
}

define hostgroup {
  hostgroup_name  foo1
  members         server1
}

define hostgroup {
  hostgroup_name  foo2
  members         server2
}

## :heavy_plus_sign: Additional context

I realize I am using older versions of the code, but I can't seem to get it to generate the line containing hostgroup_members in the definition that gets created.  I also tried a similar process to define the foo group via databags, but that also doesn't create the hostgroup_members line.

The sub-groups with the search query are working fine, it's just the parent group that seems to be giving me issues.  If I manually edit the hostgroups.cfg to add the definition for the parent group, it works as I expect, but is of course removed the next time chef-client runs.

Am I doing something incorrectly, or is this something that is not supported with the nagios cookbook?

**Comment by ramereth** [comment]
@tamwoza is this still happening with the current release?

**Comment by tamwoza** [comment]
I was able to get this working (in the versions detailed).  There was a typo found in #501 that solved my problems.
